import React, { useState } from 'react';
import { Shield, FileText, AlertTriangle, Check, Trophy, Brain } from 'lucide-react';
import DisclaimerQuiz from './DisclaimerQuiz';

interface LegalAcceptanceProps {
  onAccept: () => void;
}

export function LegalAcceptance({ onAccept }: LegalAcceptanceProps) {
  const [currentStep, setCurrentStep] = useState<'ai-warning' | 'disclaimer' | 'terms' | 'quiz' | 'done'>('ai-warning');
  const [termsAccepted, setTermsAccepted] = useState(false);
  const [disclaimerUnderstood, setDisclaimerUnderstood] = useState(false);
  const [aiWarningUnderstood, setAiWarningUnderstood] = useState(false);
  const [quizXPEarned, setQuizXPEarned] = useState(0);

  const handleAIWarningNext = () => {
    if (aiWarningUnderstood) {
      setCurrentStep('disclaimer');
    }
  };

  const handleDisclaimerNext = () => {
    if (disclaimerUnderstood) {
      setCurrentStep('terms');
    }
  };

  const handleTermsAccept = () => {
    if (termsAccepted) {
      setCurrentStep('quiz');
    }
  };

  const handleQuizComplete = (xpEarned: number) => {
    setQuizXPEarned(xpEarned);
    // Store acceptance in localStorage
    localStorage.setItem('legalAccepted', 'true');
    localStorage.setItem('legalAcceptedDate', new Date().toISOString());
    localStorage.setItem('termsVersion', '1.0');
    localStorage.setItem('quizXPEarned', xpEarned.toString());

    // Short delay to show final result, then complete
    setTimeout(() => {
      onAccept();
    }, 2000);
  };

  return (
    <div className="fixed inset-0 bg-black z-[100] flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-gradient-to-b from-slate-900 to-slate-950 rounded-3xl border border-white/20 max-w-3xl w-full p-6 md:p-8 my-8">
        {currentStep === 'ai-warning' && (
          <>
            {/* AI Warning Screen */}
            <div className="text-center mb-6">
              <div className="w-16 h-16 rounded-full bg-red-500/20 border-2 border-red-500 flex items-center justify-center mx-auto mb-4">
                <AlertTriangle size={32} className="text-red-400" />
              </div>
              <h1 className="text-2xl md:text-3xl font-bold text-white mb-2">
                🤖 CRITICAL: AI-Generated Content Warning
              </h1>
              <p className="text-red-400 font-semibold">This app uses AI - Read this BEFORE proceeding</p>
            </div>

            <div className="bg-red-500/10 border border-red-500/30 rounded-2xl p-4 mb-6">
              <p className="text-red-300 font-bold text-center">
                ⚠️ This application was created using AI and contains AI features
              </p>
            </div>

            <div className="bg-white/5 rounded-2xl border border-white/10 p-6 mb-6 max-h-96 overflow-y-auto custom-scrollbar">
              <div className="space-y-4 text-sm text-white/80">
                <div>
                  <h3 className="font-bold text-red-400 mb-2">🤖 App Created Using AI</h3>
                  <p>
                    This entire application was developed with <strong>AI assistance (Claude/ChatGPT/etc.)</strong> and may contain <strong>errors, bugs, inaccuracies, or unforeseen issues</strong>. The code has not been written by certified software engineers.
                  </p>
                </div>

                <div>
                  <h3 className="font-bold text-red-400 mb-2">🚫 AI Cannot Be Trusted for Accuracy</h3>
                  <p>
                    AI features in this app (Oracle AI, reflections, insights, document generation) are <strong>computer-generated and NOT created by licensed professionals</strong>. AI can:
                  </p>
                  <ul className="list-disc list-inside space-y-1 ml-2 mt-2">
                    <li><strong>Hallucinate</strong> - make up false information</li>
                    <li><strong>Make errors</strong> - provide incorrect advice</li>
                    <li><strong>Misunderstand context</strong> - not grasp your situation</li>
                    <li><strong>Give inappropriate suggestions</strong> - harmful or unsuitable advice</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-bold text-red-400 mb-2">✅ Your Complete Responsibility</h3>
                  <p><strong>YOU MUST:</strong></p>
                  <ul className="list-disc list-inside space-y-1 ml-2 mt-2">
                    <li><strong>Verify EVERYTHING</strong> generated by this app</li>
                    <li><strong>Check accuracy</strong> of all AI-generated content</li>
                    <li><strong>Review ALL outputs</strong> before professional use</li>
                    <li><strong>Ensure suitability</strong> for your specific purpose</li>
                    <li><strong>Make your own professional judgments</strong></li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-bold text-red-400 mb-2">❌ NEVER Do This</h3>
                  <ul className="list-disc list-inside space-y-1 ml-2">
                    <li>Submit AI-generated documentation <strong>without review</strong></li>
                    <li>Use AI suggestions for <strong>professional decisions</strong></li>
                    <li>Rely on AI for <strong>medical, legal, or financial advice</strong></li>
                    <li>Assume AI understands <strong>your regulatory requirements</strong></li>
                    <li>Trust AI-generated content as <strong>fact</strong></li>
                  </ul>
                </div>

                <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4">
                  <p className="text-red-300 font-semibold text-center text-xs">
                    ⚠️ AI is a tool to ASSIST you, not REPLACE your professional judgment.<br/>
                    ANYTHING produced using this app is YOUR responsibility to verify.
                  </p>
                </div>
              </div>
            </div>

            <label className="flex items-start gap-3 mb-6 cursor-pointer">
              <input
                type="checkbox"
                checked={aiWarningUnderstood}
                onChange={(e) => setAiWarningUnderstood(e.target.checked)}
                className="mt-1 w-5 h-5 rounded border-white/20 bg-white/10 text-cyan-500 focus:ring-2 focus:ring-cyan-500"
              />
              <span className="text-sm text-white/80">
                <strong>I understand that:</strong> This app uses AI, may contain errors, cannot be relied upon for accuracy, and I am entirely responsible for verifying everything it produces before using it professionally.
              </span>
            </label>

            <button
              onClick={handleAIWarningNext}
              disabled={!aiWarningUnderstood}
              className="w-full py-4 px-6 rounded-2xl bg-red-500 text-white font-bold hover:bg-red-600 transition disabled:opacity-50 disabled:cursor-not-allowed"
            >
              I Understand - Continue to Full Disclaimer
            </button>

            <p className="text-xs text-white/40 text-center mt-4">
              3 more steps: Disclaimer → Terms → Knowledge Quiz (earn up to 4,550 XP!)
            </p>
          </>
        )}

        {currentStep === 'disclaimer' && (
          <>
            {/* Disclaimer Screen */}
            <div className="text-center mb-6">
              <div className="w-16 h-16 rounded-full bg-amber-500/20 border-2 border-amber-500 flex items-center justify-center mx-auto mb-4">
                <AlertTriangle size={32} className="text-amber-400" />
              </div>
              <h1 className="text-2xl md:text-3xl font-bold text-white mb-2">
                Important Disclaimer
              </h1>
              <p className="text-white/60">Please read carefully before using Reflexia</p>
            </div>

            <div className="bg-white/5 rounded-2xl border border-white/10 p-6 mb-6 max-h-96 overflow-y-auto custom-scrollbar">
              <div className="space-y-4 text-sm text-white/80">
                <div>
                  <h3 className="font-bold text-white mb-2">🚨 Not Officially Endorsed</h3>
                  <p>
                    Reflexia is an <strong>independent tool</strong> and is <strong>NOT affiliated with, endorsed by, or approved by</strong> any professional regulatory body including GMC, NMC, HCPC, ACCA, SRA, Teaching Council, or any other regulatory authority.
                  </p>
                </div>

                <div>
                  <h3 className="font-bold text-white mb-2">📋 Not Official CPD Records</h3>
                  <p>
                    Reflexia is a <strong>personal productivity tool only</strong>. It is NOT a substitute for official CPD records required by your regulator. You are solely responsible for ensuring your CPD activities meet your regulatory body's requirements.
                  </p>
                </div>

                <div>
                  <h3 className="font-bold text-white mb-2">✅ Your Responsibilities</h3>
                  <ul className="list-disc list-inside space-y-1 ml-2">
                    <li>Verify all CPD requirements with YOUR regulatory body</li>
                    <li>Maintain official records as required by YOUR regulator</li>
                    <li>Check if exported formats are acceptable to YOUR regulator</li>
                    <li>Do NOT include patient-identifiable information</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-bold text-white mb-2">⚠️ No Warranties</h3>
                  <p>
                    Reflexia is provided "AS IS" with NO WARRANTIES. We are not responsible for regulatory non-compliance, rejected submissions, or professional consequences.
                  </p>
                </div>

                <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-4">
                  <p className="text-amber-200 font-semibold text-center">
                    ⚠️ Use at your own discretion. Always verify requirements with your regulatory body.
                  </p>
                </div>
              </div>
            </div>

            <label className="flex items-start gap-3 mb-6 cursor-pointer">
              <input
                type="checkbox"
                checked={disclaimerUnderstood}
                onChange={(e) => setDisclaimerUnderstood(e.target.checked)}
                className="mt-1 w-5 h-5 rounded border-white/20 bg-white/10 text-cyan-500 focus:ring-2 focus:ring-cyan-500"
              />
              <span className="text-sm text-white/80">
                I understand that Reflexia is an independent tool not affiliated with any regulatory body, and I am responsible for my own regulatory compliance.
              </span>
            </label>

            <button
              onClick={handleDisclaimerNext}
              disabled={!disclaimerUnderstood}
              className="w-full py-4 px-6 rounded-2xl bg-cyan-500 text-white font-bold hover:bg-cyan-600 transition disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Continue to Terms of Use
            </button>

            <p className="text-xs text-white/40 text-center mt-4">
              <a href="/disclaimer" target="_blank" className="underline hover:text-white">
                Read full disclaimer
              </a>
            </p>
          </>
        )}

        {currentStep === 'terms' && (
          <>
            {/* Terms of Use Screen */}
            <div className="text-center mb-6">
              <div className="w-16 h-16 rounded-full bg-cyan-500/20 border-2 border-cyan-500 flex items-center justify-center mx-auto mb-4">
                <FileText size={32} className="text-cyan-400" />
              </div>
              <h1 className="text-2xl md:text-3xl font-bold text-white mb-2">
                Terms of Use
              </h1>
              <p className="text-white/60">Agreement to use Reflexia</p>
            </div>

            <div className="bg-white/5 rounded-2xl border border-white/10 p-6 mb-6 max-h-96 overflow-y-auto custom-scrollbar">
              <div className="space-y-4 text-sm text-white/80">
                <div>
                  <h3 className="font-bold text-white mb-2">1. Acceptance of Terms</h3>
                  <p>
                    By using Reflexia, you agree to be bound by these Terms of Use, our Privacy Policy, and Refund Policy.
                  </p>
                </div>

                <div>
                  <h3 className="font-bold text-white mb-2">2. Description of Service</h3>
                  <p>
                    Reflexia is a reflection and professional development tracking tool. It is NOT medical device, NOT for clinical decisions, and NOT officially endorsed by regulatory bodies.
                  </p>
                </div>

                <div>
                  <h3 className="font-bold text-white mb-2">3. Your Data & Privacy</h3>
                  <p>
                    Your reflections are stored locally in your browser. We do NOT have access to your personal reflections or CPD records. You control and own all your data.
                  </p>
                </div>

                <div>
                  <h3 className="font-bold text-white mb-2">4. Limitation of Liability</h3>
                  <p>
                    TO THE MAXIMUM EXTENT PERMITTED BY LAW: Reflexia is provided "AS IS". We are NOT LIABLE for any damages including loss of data, regulatory non-compliance, or professional consequences.
                  </p>
                </div>

                <div>
                  <h3 className="font-bold text-white mb-2">5. Refund Policy</h3>
                  <p>
                    14-day money-back guarantee for one-time purchases. Subscriptions can be cancelled anytime with no refund for partial periods. See full Refund Policy for details.
                  </p>
                </div>

                <div className="bg-cyan-500/10 border border-cyan-500/30 rounded-xl p-4">
                  <p className="text-cyan-200 text-xs">
                    <strong>Full documents:</strong>{' '}
                    <a href="/terms" target="_blank" className="underline">Terms of Use</a>
                    {' • '}
                    <a href="/privacy-policy" target="_blank" className="underline">Privacy Policy</a>
                    {' • '}
                    <a href="/refund-policy" target="_blank" className="underline">Refund Policy</a>
                    {' • '}
                    <a href="/disclaimer" target="_blank" className="underline">Disclaimer</a>
                  </p>
                </div>
              </div>
            </div>

            <label className="flex items-start gap-3 mb-6 cursor-pointer">
              <input
                type="checkbox"
                checked={termsAccepted}
                onChange={(e) => setTermsAccepted(e.target.checked)}
                className="mt-1 w-5 h-5 rounded border-white/20 bg-white/10 text-cyan-500 focus:ring-2 focus:ring-cyan-500"
              />
              <span className="text-sm text-white/80">
                I have read and agree to the Terms of Use, Privacy Policy, Refund Policy, and Disclaimer.
              </span>
            </label>

            <div className="flex gap-3">
              <button
                onClick={() => setCurrentStep('disclaimer')}
                className="px-6 py-4 rounded-2xl bg-white/10 border border-white/20 text-white font-semibold hover:bg-white/15 transition"
              >
                Back
              </button>
              <button
                onClick={handleTermsAccept}
                disabled={!termsAccepted}
                className="flex-1 py-4 px-6 rounded-2xl bg-gradient-to-r from-cyan-500 to-indigo-500 text-white font-bold hover:scale-[1.02] transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                <Brain size={20} />
                Continue to Knowledge Quiz
              </button>
            </div>

            <p className="text-xs text-white/40 text-center mt-4">
              Complete a quick quiz to verify you've read the key information
            </p>
          </>
        )}

        {currentStep === 'quiz' && (
          <>
            {/* Quiz Introduction */}
            <div className="text-center mb-6">
              <div className="w-16 h-16 rounded-full bg-gradient-to-br from-yellow-500 to-orange-500 border-2 border-yellow-500 flex items-center justify-center mx-auto mb-4">
                <Trophy size={32} className="text-white" />
              </div>
              <h1 className="text-2xl md:text-3xl font-bold text-white mb-2">
                🎯 Knowledge Verification Quiz
              </h1>
              <p className="text-white/60">Earn high-value XP by proving you've read the disclaimers!</p>
            </div>

            <div className="bg-gradient-to-r from-yellow-500/20 to-orange-500/20 border border-yellow-500/30 rounded-2xl p-6 mb-6">
              <div className="text-center">
                <div className="text-4xl font-bold text-yellow-400 mb-2">
                  Up to 4,550 XP Available!
                </div>
                <p className="text-white/80 text-sm">
                  Answer 10 questions correctly to earn massive rewards and unlock Reflexia
                </p>
              </div>
            </div>

            <div className="bg-white/5 rounded-2xl border border-white/10 p-6 mb-6">
              <h3 className="font-bold text-white mb-3 flex items-center gap-2">
                <Brain size={20} className="text-cyan-400" />
                How it works:
              </h3>
              <ul className="space-y-2 text-sm text-white/80">
                <li className="flex items-start gap-2">
                  <Check size={16} className="text-emerald-400 flex-shrink-0 mt-0.5" />
                  <span>10 questions about critical app information</span>
                </li>
                <li className="flex items-start gap-2">
                  <Check size={16} className="text-emerald-400 flex-shrink-0 mt-0.5" />
                  <span>Each correct answer earns 400-500 XP</span>
                </li>
                <li className="flex items-start gap-2">
                  <Check size={16} className="text-emerald-400 flex-shrink-0 mt-0.5" />
                  <span>Questions test your understanding of AI warnings and disclaimers</span>
                </li>
                <li className="flex items-start gap-2">
                  <Check size={16} className="text-emerald-400 flex-shrink-0 mt-0.5" />
                  <span>Must score 80% or higher to pass</span>
                </li>
              </ul>
            </div>

            <button
              onClick={() => setCurrentStep('quiz')}
              className="w-full py-4 px-6 rounded-2xl bg-gradient-to-r from-yellow-500 to-orange-500 text-white font-bold hover:scale-[1.02] transition flex items-center justify-center gap-2"
            >
              <Trophy size={20} />
              Start Quiz & Earn Rewards
            </button>
          </>
        )}
      </div>

      {/* Quiz Modal (renders over the main modal) */}
      {currentStep === 'quiz' && (
        <DisclaimerQuiz
          onComplete={handleQuizComplete}
          onAwardXP={(amount, reason) => {
            console.log(`Quiz awarded ${amount} XP: ${reason}`);
          }}
        />
      )}
    </div>
  );
}

/**
 * Check if user has accepted legal terms
 */
export function hasAcceptedLegal(): boolean {
  return localStorage.getItem('legalAccepted') === 'true';
}

/**
 * Check if legal acceptance is still valid
 * (e.g., if terms version changed)
 */
export function isLegalAcceptanceValid(): boolean {
  const accepted = localStorage.getItem('legalAccepted');
  const version = localStorage.getItem('termsVersion');
  const currentVersion = '1.0'; // Update this when terms change

  return accepted === 'true' && version === currentVersion;
}
