import type {
  Achievement,
  ProfessionConfig,
  ReflectionModelConfig,
  ReflectionModelId,
  StageId,
} from "./types";
import { StageId as S } from "./types";

// ---------- Profession presets ----------

export const PROFESSION_CONFIG: Record<string, ProfessionConfig> = {
  NONE: {
    label: "General",
    description: "A neutral default for anyone seeking reflective practice.",
    reflectionPromptPrefix:
      "You are a reflective coach. Keep answers practical, kind, and concise.",
    modelsAllowed: ["GIBBS", "SBAR", "ERA", "ROLFE", "STAR", "SOAP", "MORNING", "EVENING", "FREE"],
  },

  // Healthcare & Clinical
  NURSING: {
    label: "Nursing",
    description: "Patient-centered reflection with clinical safety and compassionate care.",
    reflectionPromptPrefix:
      "You are a nursing reflective coach. Focus on patient safety, clinical reasoning, and compassionate care.",
    modelsAllowed: ["GIBBS", "SBAR", "SOAP", "ROLFE"],
    standards: [
      { id: "NMC_CODE", label: "NMC Code (UK)", category: "Professional Standards" },
      { id: "NMBA_STANDARDS", label: "NMBA Standards (Australia)", category: "Professional Standards" },
      { id: "NCNZ_COMPETENCIES", label: "NCNZ Competencies (New Zealand)", category: "Professional Standards" },
      { id: "CNA_CODE", label: "CNA Code of Ethics (Canada)", category: "Ethics" },
      { id: "NMBI_CODE", label: "NMBI Code (Ireland)", category: "Professional Standards" },
      { id: "SANC_SCOPE", label: "SANC Scope of Practice (South Africa)", category: "Professional Standards" },
      { id: "ANCC_STANDARDS", label: "ANCC Standards (USA)", category: "Professional Standards" },
      { id: "STATE_NURSE_ACT", label: "State Nurse Practice Acts (USA)", category: "Regulation" },
      { id: "INC_STANDARDS", label: "Indian Nursing Council Standards (India)", category: "Professional Standards" },
      { id: "NMCN_CODE", label: "NMCN Code of Conduct (Nigeria)", category: "Professional Standards" },
      { id: "PRC_NURSING", label: "PRC Nursing Code (Philippines)", category: "Professional Standards" },
      { id: "PNC_STANDARDS", label: "Pakistan Nursing Council Standards (Pakistan)", category: "Professional Standards" },
      { id: "NCK_STANDARDS", label: "Nursing Council of Kenya Standards (Kenya)", category: "Professional Standards" },
      { id: "NMC_GHANA", label: "NMC Ghana Code of Conduct (Ghana)", category: "Professional Standards" },
      { id: "SNB_STANDARDS", label: "Singapore Nursing Board Standards (Singapore)", category: "Professional Standards" },
      { id: "UNMC_CODE", label: "Uganda Nurses Council Code (Uganda)", category: "Professional Standards" },
      { id: "NCJ_STANDARDS", label: "Nursing Council of Jamaica Standards (Jamaica)", category: "Professional Standards" },
      { id: "MNB_CODE", label: "Malaysian Nursing Board Code (Malaysia)", category: "Professional Standards" },
      { id: "NCZ_STANDARDS", label: "Nurses Council of Zimbabwe Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "GNCZ_CODE", label: "General Nursing Council of Zambia Code (Zambia)", category: "Professional Standards" },
    ],
  },

  MEDICAL: {
    label: "Medical Doctor",
    description: "Clinical decision-making, diagnostic reasoning, and patient outcomes.",
    reflectionPromptPrefix:
      "You are a medical reflective coach. Focus on clinical reasoning, evidence-based practice, and patient safety.",
    modelsAllowed: ["GIBBS", "SBAR", "SOAP", "ROLFE"],
    standards: [
      { id: "GMC_GMP", label: "GMC Good Medical Practice (UK)", category: "Professional Standards" },
      { id: "AHPRA_MBA", label: "AHPRA Medical Board Standards (Australia)", category: "Regulation" },
      { id: "MCNZ_STANDARDS", label: "MCNZ Standards (New Zealand)", category: "Professional Standards" },
      { id: "CPSO_STANDARDS", label: "CPSO Standards (Canada - Ontario)", category: "Professional Standards" },
      { id: "CMPA_GUIDANCE", label: "CMPA Good Practices (Canada)", category: "Professional Standards" },
      { id: "MEDICAL_COUNCIL_IE", label: "Medical Council Standards (Ireland)", category: "Professional Standards" },
      { id: "HPCSA_GUIDELINES", label: "HPCSA Ethical Guidelines (South Africa)", category: "Ethics" },
      { id: "ACGME_COMPETENCIES", label: "ACGME Core Competencies (USA)", category: "Professional Standards" },
      { id: "ABMS_MOC", label: "ABMS Maintenance of Certification (USA)", category: "Continuing Development" },
      { id: "NMC_INDIA", label: "National Medical Commission Standards (India)", category: "Professional Standards" },
      { id: "MDCN_CODE", label: "MDCN Code of Medical Ethics (Nigeria)", category: "Ethics" },
      { id: "PMA_ETHICS", label: "Philippine Medical Association Code (Philippines)", category: "Ethics" },
      { id: "PMC_STANDARDS", label: "Pakistan Medical Commission Standards (Pakistan)", category: "Professional Standards" },
      { id: "KMPDC_STANDARDS", label: "Kenya Medical Practitioners Council Standards (Kenya)", category: "Professional Standards" },
      { id: "MDC_GHANA", label: "Medical & Dental Council Ghana Standards (Ghana)", category: "Professional Standards" },
      { id: "SMC_STANDARDS", label: "Singapore Medical Council Standards (Singapore)", category: "Professional Standards" },
      { id: "UMDPC_CODE", label: "Uganda Medical Council Code (Uganda)", category: "Professional Standards" },
      { id: "MCJ_STANDARDS", label: "Medical Council of Jamaica Standards (Jamaica)", category: "Professional Standards" },
      { id: "MMC_CODE", label: "Malaysian Medical Council Code (Malaysia)", category: "Professional Standards" },
      { id: "MDPCZ_STANDARDS", label: "Medical Council of Zimbabwe Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "HPCZ_CODE", label: "Health Professions Council of Zambia Code (Zambia)", category: "Professional Standards" },
    ],
  },

  PARAMEDIC: {
    label: "Paramedic / EMT",
    description: "High-pressure emergency response, rapid assessment, and critical interventions.",
    reflectionPromptPrefix:
      "You are an emergency medical services reflective coach. Focus on rapid decision-making, scene safety, and critical care.",
    modelsAllowed: ["SBAR", "STAR", "GIBBS", "ROLFE"],
    standards: [
      { id: "HCPC_SOP", label: "HCPC Standards of Proficiency (UK)", category: "Professional Standards" },
      { id: "PARAMEDICINE_BOARD_AU", label: "Paramedicine Board Standards (Australia)", category: "Regulation" },
      { id: "PARAMEDIC_COUNCIL_NZ", label: "Paramedic Council Standards (New Zealand)", category: "Professional Standards" },
      { id: "COPR_CANADA", label: "CoRP National Competencies (Canada)", category: "Professional Standards" },
      { id: "PHECC_IRELAND", label: "PHECC Clinical Practice Guidelines (Ireland)", category: "Clinical Guidelines" },
      { id: "HPCSA_EMERG", label: "HPCSA Emergency Care Standards (South Africa)", category: "Professional Standards" },
      { id: "NREMT_STANDARDS", label: "NREMT Standards (USA)", category: "Professional Standards" },
      { id: "COAEMSP_STANDARDS", label: "CoAEMSP Accreditation Standards (USA)", category: "Education Standards" },
      { id: "NRHM_INDIA", label: "NRHM Emergency Medical Services Standards (India)", category: "Professional Standards" },
      { id: "NPHCDA_NIGERIA", label: "NPHCDA Emergency Care Standards (Nigeria)", category: "Professional Standards" },
      { id: "DOH_EMS_PH", label: "DOH Emergency Medical Services Standards (Philippines)", category: "Professional Standards" },
      { id: "PHRC_PAKISTAN", label: "Pakistan Health Research Council EMS Guidelines (Pakistan)", category: "Professional Standards" },
      { id: "MOH_EMS_KENYA", label: "Ministry of Health EMS Standards (Kenya)", category: "Professional Standards" },
      { id: "GHS_EMS_GHANA", label: "Ghana Health Service EMS Standards (Ghana)", category: "Professional Standards" },
      { id: "SCDF_STANDARDS", label: "SCDF Paramedic Standards (Singapore)", category: "Professional Standards" },
      { id: "MOH_EMS_UGANDA", label: "Ministry of Health EMS Guidelines (Uganda)", category: "Professional Standards" },
      { id: "MOHW_EMS_JM", label: "Ministry of Health EMS Standards (Jamaica)", category: "Professional Standards" },
      { id: "MOH_EMS_MY", label: "Ministry of Health Emergency Services Standards (Malaysia)", category: "Professional Standards" },
      { id: "MOHCC_EMS_ZW", label: "MOHCC Emergency Care Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "MOH_EMS_ZM", label: "Ministry of Health EMS Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  MENTAL_HEALTH: {
    label: "Mental Health / Therapy",
    description: "Therapeutic relationships, clinical boundaries, and evidence-based interventions.",
    reflectionPromptPrefix:
      "You are a mental health reflective coach. Focus on therapeutic process, boundaries, and client-centered care.",
    modelsAllowed: ["GIBBS", "ROLFE", "ERA", "SOAP"],
    standards: [
      { id: "BACP_ETHICS", label: "BACP Ethical Framework (UK)", category: "Ethics" },
      { id: "BPS_CODE", label: "BPS Code of Ethics (UK)", category: "Ethics" },
      { id: "PACFA_STANDARDS", label: "PACFA Standards (Australia)", category: "Professional Standards" },
      { id: "APS_CODE", label: "APS Code of Ethics (Australia)", category: "Ethics" },
      { id: "NZAC_CODE", label: "NZAC Code of Ethics (New Zealand)", category: "Ethics" },
      { id: "NZPS_CODE", label: "NZPS Code of Ethics (New Zealand)", category: "Ethics" },
      { id: "CCPA_CODE", label: "CCPA Code of Ethics (Canada)", category: "Ethics" },
      { id: "CPA_CODE", label: "CPA Code of Ethics (Canada)", category: "Ethics" },
      { id: "IACP_CODE", label: "IACP Code of Ethics (Ireland)", category: "Ethics" },
      { id: "HPCSA_PSYCH", label: "HPCSA Psychology Board Guidelines (South Africa)", category: "Professional Standards" },
      { id: "APA_ETHICS", label: "APA Ethics Code (USA)", category: "Ethics" },
      { id: "NASW_CODE", label: "NASW Code of Ethics (USA)", category: "Ethics" },
      { id: "ACA_CODE", label: "ACA Code of Ethics (USA)", category: "Ethics" },
      { id: "RCI_CODE", label: "Rehabilitation Council of India Code (India)", category: "Ethics" },
      { id: "ANPPCAN_CODE", label: "ANPPCAN Mental Health Guidelines (Nigeria)", category: "Professional Standards" },
      { id: "PAP_CODE", label: "Psychological Association of the Philippines Code (Philippines)", category: "Ethics" },
      { id: "PPCP_CODE", label: "Pakistan Psychological Council Code (Pakistan)", category: "Ethics" },
      { id: "KPSB_CODE", label: "Kenya Psychological Society Standards (Kenya)", category: "Professional Standards" },
      { id: "GAPSYA_CODE", label: "Ghana Association of Psychologists Code (Ghana)", category: "Ethics" },
      { id: "SPS_CODE", label: "Singapore Psychological Society Code (Singapore)", category: "Ethics" },
      { id: "UPA_GUIDELINES", label: "Uganda Psychological Association Guidelines (Uganda)", category: "Professional Standards" },
      { id: "JPA_CODE", label: "Jamaica Psychological Society Code (Jamaica)", category: "Ethics" },
      { id: "PSIMA_CODE", label: "Psychological Society of Malaysia Code (Malaysia)", category: "Ethics" },
      { id: "ZPSA_CODE", label: "Zimbabwe Psychological Society Code (Zimbabwe)", category: "Ethics" },
      { id: "ZAPS_CODE", label: "Zambia Association of Psychology Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  SOCIAL_WORK: {
    label: "Social Work",
    description: "Advocacy, safeguarding, and person-centered support.",
    reflectionPromptPrefix:
      "You are a social work reflective coach. Focus on advocacy, safeguarding, and empowerment.",
    modelsAllowed: ["GIBBS", "ROLFE", "ERA", "SBAR"],
    standards: [
      { id: "SWE_STANDARDS", label: "Social Work England Standards (UK)", category: "Professional Standards" },
      { id: "BASW_CODE", label: "BASW Code of Ethics (UK)", category: "Ethics" },
      { id: "AASW_CODE", label: "AASW Code of Ethics (Australia)", category: "Ethics" },
      { id: "SWRB_COMPETENCIES", label: "SWRB Competencies (New Zealand)", category: "Professional Standards" },
      { id: "ANZASW_CODE", label: "ANZASW Code of Ethics (New Zealand)", category: "Ethics" },
      { id: "CASW_CODE", label: "CASW Code of Ethics (Canada)", category: "Ethics" },
      { id: "CORU_STANDARDS", label: "CORU Standards (Ireland)", category: "Professional Standards" },
      { id: "SACSSP_POLICY", label: "SACSSP Policy Guidelines (South Africa)", category: "Professional Standards" },
      { id: "NASW_CODE_US", label: "NASW Code of Ethics (USA)", category: "Ethics" },
      { id: "CSWE_COMPETENCIES", label: "CSWE Educational Competencies (USA)", category: "Education Standards" },
      { id: "ICSSW_CODE", label: "Indian Council for Social Work Code (India)", category: "Ethics" },
      { id: "SWAN_CODE", label: "Social Workers Association of Nigeria Code (Nigeria)", category: "Ethics" },
      { id: "PASWI_CODE", label: "Philippine Association of Social Workers Code (Philippines)", category: "Ethics" },
      { id: "PCSW_CODE", label: "Pakistan Council for Social Welfare Code (Pakistan)", category: "Ethics" },
      { id: "KASWEP_CODE", label: "Kenya Association of Social Workers Code (Kenya)", category: "Ethics" },
      { id: "GNASP_CODE", label: "Ghana National Association of Social Workers Code (Ghana)", category: "Ethics" },
      { id: "SASW_CODE", label: "Singapore Association of Social Workers Code (Singapore)", category: "Ethics" },
      { id: "UASW_CODE", label: "Uganda Association of Social Workers Code (Uganda)", category: "Ethics" },
      { id: "JASW_CODE", label: "Jamaica Association of Social Workers Code (Jamaica)", category: "Ethics" },
      { id: "MASW_CODE", label: "Malaysian Association of Social Workers Code (Malaysia)", category: "Ethics" },
      { id: "SASW_ZW_CODE", label: "Social Workers Association of Zimbabwe Code (Zimbabwe)", category: "Ethics" },
      { id: "ZASW_CODE", label: "Zambia Association of Social Workers Code (Zambia)", category: "Ethics" },
    ],
  },

  PHARMACY: {
    label: "Pharmacy",
    description: "Medication safety, patient counseling, and pharmaceutical care.",
    reflectionPromptPrefix:
      "You are a pharmacy reflective coach. Focus on medication safety, patient education, and clinical outcomes.",
    modelsAllowed: ["GIBBS", "SBAR", "SOAP", "ROLFE"],
    standards: [
      { id: "GPHC_STANDARDS", label: "GPhC Standards (UK)", category: "Professional Standards" },
      { id: "PSA_STANDARDS", label: "PSA Standards (Australia)", category: "Professional Standards" },
      { id: "PCNZ_STANDARDS", label: "Pharmacy Council NZ Standards (New Zealand)", category: "Professional Standards" },
      { id: "NAPRA_STANDARDS", label: "NAPRA Standards (Canada)", category: "Professional Standards" },
      { id: "PSI_STANDARDS", label: "PSI Standards (Ireland)", category: "Professional Standards" },
      { id: "SAPC_GPP", label: "SAPC Good Pharmacy Practice (South Africa)", category: "Professional Standards" },
      { id: "NABP_MPJE", label: "NABP Model Rules (USA)", category: "Regulation" },
      { id: "STATE_PHARMACY_ACT", label: "State Pharmacy Practice Acts (USA)", category: "Regulation" },
      { id: "PCI_INDIA", label: "Pharmacy Council of India Standards (India)", category: "Professional Standards" },
      { id: "PCN_NIGERIA", label: "Pharmacists Council of Nigeria Code (Nigeria)", category: "Ethics" },
      { id: "PRC_PHARMACY_PH", label: "PRC Pharmacy Board Standards (Philippines)", category: "Professional Standards" },
      { id: "PCP_PAKISTAN", label: "Pharmacy Council of Pakistan Standards (Pakistan)", category: "Professional Standards" },
      { id: "PPB_KENYA", label: "Pharmacy and Poisons Board Standards (Kenya)", category: "Professional Standards" },
      { id: "PCG_GHANA", label: "Pharmacy Council Ghana Standards (Ghana)", category: "Professional Standards" },
      { id: "SPC_SINGAPORE", label: "Singapore Pharmacy Council Standards (Singapore)", category: "Professional Standards" },
      { id: "PCU_UGANDA", label: "Pharmacy Council of Uganda Standards (Uganda)", category: "Professional Standards" },
      { id: "PCJ_JAMAICA", label: "Pharmacy Council of Jamaica Standards (Jamaica)", category: "Professional Standards" },
      { id: "MPC_MALAYSIA", label: "Malaysian Pharmacy Board Standards (Malaysia)", category: "Professional Standards" },
      { id: "PCZ_ZIMBABWE", label: "Pharmacy Council of Zimbabwe Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "HPC_ZAMBIA", label: "Health Professions Council Pharmacy Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  DENTISTRY: {
    label: "Dentistry",
    description: "Clinical skills, patient care, and preventive oral health.",
    reflectionPromptPrefix:
      "You are a dental reflective coach. Focus on clinical excellence, patient communication, and preventive care.",
    modelsAllowed: ["GIBBS", "SBAR", "SOAP", "ROLFE"],
    standards: [
      { id: "GDC_STANDARDS", label: "GDC Standards for the Dental Team (UK)", category: "Professional Standards" },
      { id: "AHPRA_DENTAL", label: "Dental Board of Australia Standards (Australia)", category: "Regulation" },
      { id: "DCNZ_STANDARDS", label: "DCNZ Standards (New Zealand)", category: "Professional Standards" },
      { id: "NDEB_COMPETENCIES", label: "NDEB Competencies (Canada)", category: "Professional Standards" },
      { id: "DENTAL_COUNCIL_IE", label: "Dental Council Standards (Ireland)", category: "Professional Standards" },
      { id: "HPCSA_DENTAL", label: "HPCSA Dental Therapy Guidelines (South Africa)", category: "Professional Standards" },
      { id: "ADA_PRINCIPLES", label: "ADA Principles of Ethics (USA)", category: "Ethics" },
      { id: "DCI_INDIA", label: "Dental Council of India Standards (India)", category: "Professional Standards" },
      { id: "MDC_NIGERIA", label: "Medical & Dental Council of Nigeria Standards (Nigeria)", category: "Professional Standards" },
      { id: "PRC_DENTAL_PH", label: "PRC Dentistry Board Standards (Philippines)", category: "Professional Standards" },
      { id: "PMDC_DENTAL", label: "Pakistan Medical & Dental Council Standards (Pakistan)", category: "Professional Standards" },
      { id: "KDA_STANDARDS", label: "Kenya Dental Association Standards (Kenya)", category: "Professional Standards" },
      { id: "MDCG_GHANA", label: "Medical & Dental Council Ghana Standards (Ghana)", category: "Professional Standards" },
      { id: "SDC_SINGAPORE", label: "Singapore Dental Council Standards (Singapore)", category: "Professional Standards" },
      { id: "ADC_UGANDA", label: "Allied Dental Council Standards (Uganda)", category: "Professional Standards" },
      { id: "DCJ_JAMAICA", label: "Dental Council of Jamaica Standards (Jamaica)", category: "Professional Standards" },
      { id: "MDC_MALAYSIA", label: "Malaysian Dental Council Standards (Malaysia)", category: "Professional Standards" },
      { id: "MDTCZ_ZIMBABWE", label: "Medical & Dental Council of Zimbabwe Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "HPC_DENTAL_ZM", label: "Health Professions Council Dental Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  ALLIED_HEALTH: {
    label: "Allied Health",
    description: "Physiotherapy, occupational therapy, speech therapy, and rehabilitation.",
    reflectionPromptPrefix:
      "You are an allied health reflective coach. Focus on patient-centered rehabilitation and functional outcomes.",
    modelsAllowed: ["GIBBS", "SBAR", "ROLFE", "ERA"],
    standards: [
      { id: "HCPC_ALLIED", label: "HCPC Standards (UK)", category: "Professional Standards" },
      { id: "AHPRA_PHYSIO", label: "Physiotherapy Board Standards (Australia)", category: "Regulation" },
      { id: "AHPRA_OT", label: "Occupational Therapy Board Standards (Australia)", category: "Regulation" },
      { id: "PHYSIO_BOARD_NZ", label: "Physiotherapy Board Standards (New Zealand)", category: "Professional Standards" },
      { id: "CAOT_PROFILE", label: "CAOT Profile of Practice (Canada)", category: "Professional Standards" },
      { id: "CORU_PHYSIO", label: "CORU Physio Standards (Ireland)", category: "Professional Standards" },
      { id: "HPCSA_ALLIED", label: "HPCSA Allied Health Standards (South Africa)", category: "Professional Standards" },
      { id: "APTA_CODE", label: "APTA Code of Ethics (USA)", category: "Ethics" },
      { id: "AOTA_CODE", label: "AOTA Code of Ethics (USA)", category: "Ethics" },
      { id: "IAP_INDIA", label: "Indian Association of Physiotherapists Standards (India)", category: "Professional Standards" },
      { id: "NSP_NIGERIA", label: "Nigeria Society of Physiotherapy Code (Nigeria)", category: "Ethics" },
      { id: "PAP_PH", label: "Philippine Association of Physical Therapists Standards (Philippines)", category: "Professional Standards" },
      { id: "PPA_PAKISTAN", label: "Pakistan Physiotherapy Association Standards (Pakistan)", category: "Professional Standards" },
      { id: "KSP_KENYA", label: "Kenya Society of Physiotherapists Standards (Kenya)", category: "Professional Standards" },
      { id: "GPSN_GHANA", label: "Ghana Physiotherapy Society Standards (Ghana)", category: "Professional Standards" },
      { id: "SPA_SINGAPORE", label: "Singapore Physiotherapy Association Standards (Singapore)", category: "Professional Standards" },
      { id: "UAP_UGANDA", label: "Uganda Association of Physiotherapists Standards (Uganda)", category: "Professional Standards" },
      { id: "JAPT_JAMAICA", label: "Jamaica Association of Physical Therapists Standards (Jamaica)", category: "Professional Standards" },
      { id: "MSP_MALAYSIA", label: "Malaysian Society of Physiotherapists Standards (Malaysia)", category: "Professional Standards" },
      { id: "ZSP_ZIMBABWE", label: "Zimbabwe Society of Physiotherapists Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "ZSP_ZAMBIA", label: "Zambia Society of Physiotherapy Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  // Emergency & Public Safety
  EMERGENCY_SERVICES: {
    label: "Emergency Services",
    description: "Critical incident response, team coordination, and public safety.",
    reflectionPromptPrefix:
      "You are an emergency services reflective coach. Focus on incident management, team dynamics, and safety protocols.",
    modelsAllowed: ["SBAR", "STAR", "GIBBS", "ROLFE"],
    standards: [
      { id: "NFCC_CODE", label: "NFCC Code of Ethics (UK)", category: "Ethics" },
      { id: "JESIP_PRINCIPLES", label: "JESIP Joint Decision Model (UK)", category: "Operational Standards" },
      { id: "AFAC_STANDARDS", label: "AFAC Standards (Australia)", category: "Professional Standards" },
      { id: "CDEM_ACT", label: "CDEM Act Guidelines (New Zealand)", category: "Regulation" },
      { id: "NFPA_STANDARDS", label: "NFPA Standards (USA/Canada/International)", category: "Professional Standards" },
      { id: "ICS_STANDARDS", label: "ICS/NIMS Standards (USA)", category: "Operational Standards" },
      { id: "NDMA_INDIA", label: "National Disaster Management Authority Standards (India)", category: "Professional Standards" },
      { id: "NEMA_NIGERIA", label: "NEMA Emergency Response Standards (Nigeria)", category: "Professional Standards" },
      { id: "NDRRMC_PH", label: "NDRRMC Emergency Response Standards (Philippines)", category: "Professional Standards" },
      { id: "NDMA_PAKISTAN", label: "National Disaster Management Authority Standards (Pakistan)", category: "Professional Standards" },
      { id: "NEMA_KENYA", label: "National Emergency Management Authority Standards (Kenya)", category: "Professional Standards" },
      { id: "NADMO_GHANA", label: "NADMO Emergency Standards (Ghana)", category: "Professional Standards" },
      { id: "SCDF_SINGAPORE", label: "Singapore Civil Defence Force Standards (Singapore)", category: "Professional Standards" },
      { id: "OPM_UGANDA", label: "Office of Prime Minister Emergency Standards (Uganda)", category: "Professional Standards" },
      { id: "ODPEM_JAMAICA", label: "ODPEM Emergency Management Standards (Jamaica)", category: "Professional Standards" },
      { id: "NADMA_MALAYSIA", label: "National Disaster Management Agency Standards (Malaysia)", category: "Professional Standards" },
      { id: "DCP_ZIMBABWE", label: "Department of Civil Protection Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "DMMU_ZAMBIA", label: "Disaster Management Unit Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  LAW_ENFORCEMENT: {
    label: "Law Enforcement",
    description: "Public safety, ethical decision-making, and community relations.",
    reflectionPromptPrefix:
      "You are a law enforcement reflective coach. Focus on ethical decision-making, de-escalation, and community trust.",
    modelsAllowed: ["STAR", "GIBBS", "ROLFE", "SBAR"],
    standards: [
      { id: "COLLEGE_POLICING_UK", label: "College of Policing Code of Ethics (UK)", category: "Ethics" },
      { id: "ANZPAA_STANDARDS", label: "ANZPAA Standards (Australia)", category: "Professional Standards" },
      { id: "IPCA_GUIDELINES", label: "IPCA Guidelines (New Zealand)", category: "Professional Standards" },
      { id: "RCMP_CODE", label: "RCMP Code of Conduct (Canada)", category: "Ethics" },
      { id: "GSOC_CODE", label: "Garda Code of Ethics (Ireland)", category: "Ethics" },
      { id: "SAPS_CODE", label: "SAPS Code of Conduct (South Africa)", category: "Ethics" },
      { id: "CALEA_STANDARDS", label: "CALEA Accreditation Standards (USA)", category: "Professional Standards" },
      { id: "STATE_POST", label: "State POST Standards (USA)", category: "Training Standards" },
      { id: "IACP_ETHICS", label: "IACP Law Enforcement Code of Ethics (USA)", category: "Ethics" },
      { id: "BPR&D_INDIA", label: "Bureau of Police Research & Development Standards (India)", category: "Professional Standards" },
      { id: "NPF_CODE_NIGERIA", label: "Nigeria Police Force Code of Conduct (Nigeria)", category: "Ethics" },
      { id: "PNP_CODE_PH", label: "Philippine National Police Code of Conduct (Philippines)", category: "Ethics" },
      { id: "NACTA_PAKISTAN", label: "NACTA Law Enforcement Standards (Pakistan)", category: "Professional Standards" },
      { id: "NPS_CODE_KENYA", label: "National Police Service Code of Conduct (Kenya)", category: "Ethics" },
      { id: "GPS_CODE_GHANA", label: "Ghana Police Service Code of Ethics (Ghana)", category: "Ethics" },
      { id: "SPF_CODE_SINGAPORE", label: "Singapore Police Force Code of Conduct (Singapore)", category: "Ethics" },
      { id: "UPF_CODE_UGANDA", label: "Uganda Police Force Code of Conduct (Uganda)", category: "Ethics" },
      { id: "JCF_CODE_JAMAICA", label: "Jamaica Constabulary Force Code of Ethics (Jamaica)", category: "Ethics" },
      { id: "PDRM_CODE_MALAYSIA", label: "Royal Malaysia Police Code of Ethics (Malaysia)", category: "Ethics" },
      { id: "ZRP_CODE_ZIMBABWE", label: "Zimbabwe Republic Police Code of Conduct (Zimbabwe)", category: "Ethics" },
      { id: "ZPS_CODE_ZAMBIA", label: "Zambia Police Service Code of Conduct (Zambia)", category: "Ethics" },
    ],
  },

  FIRE_RESCUE: {
    label: "Fire & Rescue",
    description: "Operational safety, teamwork, and emergency response.",
    reflectionPromptPrefix:
      "You are a fire & rescue reflective coach. Focus on operational safety, team coordination, and incident command.",
    modelsAllowed: ["SBAR", "STAR", "GIBBS", "ROLFE"],
    standards: [
      { id: "NFCC_STANDARDS_UK", label: "NFCC Core Code of Ethics (UK)", category: "Ethics" },
      { id: "FRS_ACT_UK", label: "Fire and Rescue Services Act (UK)", category: "Regulation" },
      { id: "AFAC_DOCTRINE", label: "AFAC Doctrine (Australia)", category: "Operational Standards" },
      { id: "FENZ_STANDARDS", label: "Fire and Emergency NZ Standards (New Zealand)", category: "Professional Standards" },
      { id: "NFPA_1500", label: "NFPA 1500 Fire Department Safety (International)", category: "Safety Standards" },
      { id: "NFPA_1021", label: "NFPA 1021 Fire Officer Standards (International)", category: "Professional Standards" },
      { id: "ICS_NIMS", label: "ICS/NIMS (USA)", category: "Operational Standards" },
      { id: "NFSC_INDIA", label: "National Fire Service College Standards (India)", category: "Professional Standards" },
      { id: "FFS_NIGERIA", label: "Federal Fire Service Standards (Nigeria)", category: "Professional Standards" },
      { id: "BFP_CODE_PH", label: "Bureau of Fire Protection Code (Philippines)", category: "Ethics" },
      { id: "RESCUE1122_PK", label: "Rescue 1122 Service Standards (Pakistan)", category: "Professional Standards" },
      { id: "NFBK_STANDARDS", label: "National Fire Brigade Kenya Standards (Kenya)", category: "Professional Standards" },
      { id: "GNFS_CODE", label: "Ghana National Fire Service Code (Ghana)", category: "Ethics" },
      { id: "SCDF_FIRE_SG", label: "SCDF Fire Safety Standards (Singapore)", category: "Professional Standards" },
      { id: "KCCA_FIRE_UG", label: "KCCA Fire Brigade Standards (Uganda)", category: "Professional Standards" },
      { id: "JFB_CODE", label: "Jamaica Fire Brigade Code (Jamaica)", category: "Ethics" },
      { id: "BOMBA_CODE", label: "Bomba Malaysia Fire Service Code (Malaysia)", category: "Ethics" },
      { id: "ZBFS_CODE", label: "Zimbabwe Brigade Fire Service Code (Zimbabwe)", category: "Ethics" },
      { id: "ZFS_CODE", label: "Zambia Fire Service Code (Zambia)", category: "Ethics" },
    ],
  },

  MILITARY: {
    label: "Military / Defense",
    description: "Leadership under pressure, mission execution, and team cohesion.",
    reflectionPromptPrefix:
      "You are a military reflective coach. Focus on mission effectiveness, leadership, and team resilience.",
    modelsAllowed: ["STAR", "GIBBS", "ROLFE", "SBAR"],
    standards: [
      { id: "VALUES_STANDARDS_UK", label: "Armed Forces Values and Standards (UK)", category: "Professional Standards" },
      { id: "ADF_VALUES", label: "ADF Values (Australia)", category: "Professional Standards" },
      { id: "NZDF_VALUES", label: "NZDF Values (New Zealand)", category: "Professional Standards" },
      { id: "CAF_ETHOS", label: "CAF Ethos (Canada)", category: "Professional Standards" },
      { id: "SANDF_CODE", label: "SANDF Code of Conduct (South Africa)", category: "Ethics" },
      { id: "UCMJ", label: "Uniform Code of Military Justice (USA)", category: "Regulation" },
      { id: "DOD_VALUES", label: "DoD Core Values (USA)", category: "Professional Standards" },
      { id: "INDIAN_ARMY_VALUES", label: "Indian Armed Forces Values (India)", category: "Professional Standards" },
      { id: "NAF_CODE", label: "Nigerian Armed Forces Code (Nigeria)", category: "Ethics" },
      { id: "AFP_CODE_PH", label: "Armed Forces of the Philippines Code (Philippines)", category: "Ethics" },
      { id: "PAF_CODE_PK", label: "Pakistan Armed Forces Code (Pakistan)", category: "Ethics" },
      { id: "KDF_CODE", label: "Kenya Defence Forces Code (Kenya)", category: "Ethics" },
      { id: "GAF_CODE", label: "Ghana Armed Forces Code (Ghana)", category: "Ethics" },
      { id: "SAF_VALUES", label: "Singapore Armed Forces Core Values (Singapore)", category: "Professional Standards" },
      { id: "UPDF_CODE", label: "Uganda People's Defence Force Code (Uganda)", category: "Ethics" },
      { id: "JDF_CODE", label: "Jamaica Defence Force Code (Jamaica)", category: "Ethics" },
      { id: "MAF_CODE", label: "Malaysian Armed Forces Code (Malaysia)", category: "Ethics" },
      { id: "ZDF_CODE", label: "Zimbabwe Defence Forces Code (Zimbabwe)", category: "Ethics" },
      { id: "ZAF_CODE", label: "Zambia Air Force Code (Zambia)", category: "Ethics" },
    ],
  },

  // Education & Development
  TEACHING_PRIMARY: {
    label: "Primary Teaching",
    description: "Child development, learning outcomes, and classroom management.",
    reflectionPromptPrefix:
      "You are a primary education reflective coach. Focus on learning outcomes, child development, and inclusive practice.",
    modelsAllowed: ["GIBBS", "ROLFE", "ERA", "STAR"],
    standards: [
      { id: "TEACHERS_STANDARDS_UK", label: "Teachers' Standards (UK)", category: "Professional Standards" },
      { id: "AITSL_STANDARDS", label: "AITSL Australian Professional Standards (Australia)", category: "Professional Standards" },
      { id: "TEACHING_COUNCIL_NZ", label: "Teaching Council Standards (New Zealand)", category: "Professional Standards" },
      { id: "OCT_STANDARDS", label: "OCT Standards of Practice (Canada - Ontario)", category: "Professional Standards" },
      { id: "TEACHING_COUNCIL_IE", label: "Teaching Council Code of Conduct (Ireland)", category: "Ethics" },
      { id: "SACE_STANDARDS", label: "SACE Professional Standards (South Africa)", category: "Professional Standards" },
      { id: "INTASC_STANDARDS", label: "InTASC Model Core Teaching Standards (USA)", category: "Professional Standards" },
      { id: "NAEYC_STANDARDS", label: "NAEYC Standards (USA)", category: "Early Childhood Standards" },
      { id: "NCTE_INDIA", label: "National Council for Teacher Education Standards (India)", category: "Professional Standards" },
      { id: "TRCN_NIGERIA", label: "Teachers Registration Council of Nigeria Standards (Nigeria)", category: "Professional Standards" },
      { id: "PRC_TEACHERS_PH", label: "PRC Professional Teachers Board Standards (Philippines)", category: "Professional Standards" },
      { id: "NITB_PAKISTAN", label: "National Institute of Teacher Education Standards (Pakistan)", category: "Professional Standards" },
      { id: "TSC_KENYA", label: "Teachers Service Commission Standards (Kenya)", category: "Professional Standards" },
      { id: "NTC_GHANA", label: "National Teaching Council Standards (Ghana)", category: "Professional Standards" },
      { id: "NIE_SINGAPORE", label: "National Institute of Education Standards (Singapore)", category: "Professional Standards" },
      { id: "UNEB_UGANDA", label: "Uganda National Examinations Board Teaching Standards (Uganda)", category: "Professional Standards" },
      { id: "JTC_JAMAICA", label: "Jamaica Teaching Council Standards (Jamaica)", category: "Professional Standards" },
      { id: "LPM_MALAYSIA", label: "Lembaga Pendidikan Malaysia Teaching Standards (Malaysia)", category: "Professional Standards" },
      { id: "TSC_ZIMBABWE", label: "Teacher Service Commission Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "GTCZ_ZAMBIA", label: "General Teaching Council of Zambia Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  TEACHING_SECONDARY: {
    label: "Secondary Teaching",
    description: "Subject mastery, student engagement, and assessment strategies.",
    reflectionPromptPrefix:
      "You are a secondary education reflective coach. Focus on pedagogy, student progress, and curriculum delivery.",
    modelsAllowed: ["GIBBS", "ROLFE", "ERA", "STAR"],
    standards: [
      { id: "TEACHERS_STANDARDS_UK", label: "Teachers' Standards (UK)", category: "Professional Standards" },
      { id: "AITSL_STANDARDS", label: "AITSL Australian Professional Standards (Australia)", category: "Professional Standards" },
      { id: "TEACHING_COUNCIL_NZ", label: "Teaching Council Standards (New Zealand)", category: "Professional Standards" },
      { id: "OCT_STANDARDS", label: "OCT Standards of Practice (Canada - Ontario)", category: "Professional Standards" },
      { id: "TEACHING_COUNCIL_IE", label: "Teaching Council Code of Conduct (Ireland)", category: "Ethics" },
      { id: "SACE_STANDARDS", label: "SACE Professional Standards (South Africa)", category: "Professional Standards" },
      { id: "INTASC_STANDARDS", label: "InTASC Model Core Teaching Standards (USA)", category: "Professional Standards" },
      { id: "NBPTS_STANDARDS", label: "NBPTS Core Propositions (USA)", category: "Professional Standards" },
      { id: "NCTE_SECONDARY_INDIA", label: "NCTE Secondary Education Standards (India)", category: "Professional Standards" },
      { id: "TRCN_SECONDARY_NG", label: "TRCN Secondary School Standards (Nigeria)", category: "Professional Standards" },
      { id: "CHED_PH", label: "Commission on Higher Education Standards (Philippines)", category: "Professional Standards" },
      { id: "HEC_PAKISTAN", label: "Higher Education Commission Standards (Pakistan)", category: "Professional Standards" },
      { id: "TSC_SECONDARY_KE", label: "TSC Secondary School Standards (Kenya)", category: "Professional Standards" },
      { id: "GES_GHANA", label: "Ghana Education Service Standards (Ghana)", category: "Professional Standards" },
      { id: "MOE_SINGAPORE", label: "Ministry of Education Teaching Standards (Singapore)", category: "Professional Standards" },
      { id: "MES_UGANDA", label: "Ministry of Education & Sports Standards (Uganda)", category: "Professional Standards" },
      { id: "MOEY_JAMAICA", label: "Ministry of Education & Youth Standards (Jamaica)", category: "Professional Standards" },
      { id: "MOE_MALAYSIA", label: "Ministry of Education Malaysia Standards (Malaysia)", category: "Professional Standards" },
      { id: "ZIMSEC_STANDARDS", label: "ZIMSEC Teaching Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "ECZ_ZAMBIA", label: "Examinations Council of Zambia Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  TEACHING_HIGHER: {
    label: "Higher Education",
    description: "Research-informed teaching, critical thinking, and academic development.",
    reflectionPromptPrefix:
      "You are a higher education reflective coach. Focus on scholarship, critical inquiry, and student development.",
    modelsAllowed: ["GIBBS", "ROLFE", "ERA"],
    standards: [
      { id: "UKPSF", label: "UK Professional Standards Framework (UK)", category: "Professional Standards" },
      { id: "HEA_FRAMEWORK", label: "Advance HE Framework (UK)", category: "Professional Standards" },
      { id: "TEQSA_STANDARDS", label: "TEQSA Standards (Australia)", category: "Regulation" },
      { id: "PBRF_STANDARDS", label: "PBRF Quality Standards (New Zealand)", category: "Research Standards" },
      { id: "SEDA_VALUES", label: "SEDA Values (UK/International)", category: "Professional Standards" },
      { id: "UGC_INDIA", label: "University Grants Commission Standards (India)", category: "Professional Standards" },
      { id: "NUC_NIGERIA", label: "National Universities Commission Standards (Nigeria)", category: "Professional Standards" },
      { id: "CHED_HE_PH", label: "CHED Higher Education Quality Standards (Philippines)", category: "Professional Standards" },
      { id: "HEC_HE_PAKISTAN", label: "HEC Academic Quality Standards (Pakistan)", category: "Professional Standards" },
      { id: "CUE_KENYA", label: "Commission for University Education Standards (Kenya)", category: "Professional Standards" },
      { id: "NAB_GHANA", label: "National Accreditation Board Standards (Ghana)", category: "Professional Standards" },
      { id: "SQC_SINGAPORE", label: "Singapore Quality Class for Universities (Singapore)", category: "Professional Standards" },
      { id: "NCHE_UGANDA", label: "National Council for Higher Education Standards (Uganda)", category: "Professional Standards" },
      { id: "UCJ_JAMAICA", label: "University Council of Jamaica Standards (Jamaica)", category: "Professional Standards" },
      { id: "MQA_MALAYSIA", label: "Malaysian Qualifications Agency Standards (Malaysia)", category: "Professional Standards" },
      { id: "ZIMCHE_ZIMBABWE", label: "Zimbabwe Council for Higher Education Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "HEA_ZAMBIA", label: "Higher Education Authority Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  EDUCATION: {
    label: "Education (General)",
    description: "Learning outcomes, student support, and educational practice.",
    reflectionPromptPrefix:
      "You are an education reflective coach. Focus on outcomes, clarity, and next actions.",
    modelsAllowed: ["GIBBS", "ROLFE", "ERA", "STAR"],
    standards: [
      { id: "TEACHERS_STANDARDS_UK", label: "Teachers' Standards (UK)", category: "Professional Standards" },
      { id: "AITSL_STANDARDS", label: "AITSL Standards (Australia)", category: "Professional Standards" },
      { id: "TEACHING_COUNCIL_NZ", label: "Teaching Council Standards (New Zealand)", category: "Professional Standards" },
      { id: "INTASC_STANDARDS", label: "InTASC Standards (USA)", category: "Professional Standards" },
      { id: "NCTE_GENERAL_INDIA", label: "NCTE General Education Standards (India)", category: "Professional Standards" },
      { id: "TRCN_GENERAL_NG", label: "TRCN General Teaching Standards (Nigeria)", category: "Professional Standards" },
      { id: "DEPED_PH", label: "DepEd Teaching Standards (Philippines)", category: "Professional Standards" },
      { id: "AEPAM_PAKISTAN", label: "Academy of Educational Planning Standards (Pakistan)", category: "Professional Standards" },
      { id: "TSC_GENERAL_KE", label: "TSC General Teaching Standards (Kenya)", category: "Professional Standards" },
      { id: "NTC_GENERAL_GH", label: "NTC General Education Standards (Ghana)", category: "Professional Standards" },
      { id: "NIE_GENERAL_SG", label: "NIE General Education Standards (Singapore)", category: "Professional Standards" },
      { id: "ESC_UGANDA", label: "Education Service Commission Standards (Uganda)", category: "Professional Standards" },
      { id: "MOEY_GENERAL_JM", label: "MOEY General Education Standards (Jamaica)", category: "Professional Standards" },
      { id: "KPM_MALAYSIA", label: "KPM General Education Standards (Malaysia)", category: "Professional Standards" },
      { id: "MOPSE_ZIMBABWE", label: "Ministry of Primary & Secondary Education Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "MESVTEE_ZAMBIA", label: "Ministry of Education Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  // Social Care & Support
  SOCIAL_CARE: {
    label: "Social Care",
    description: "Person-centered care, dignity, and safeguarding.",
    reflectionPromptPrefix:
      "You are a social care reflective coach. Focus on person-centered practice, dignity, and safeguarding.",
    modelsAllowed: ["GIBBS", "ROLFE", "ERA", "SBAR"],
    standards: [
      { id: "CQC_FUNDAMENTAL", label: "CQC Fundamental Standards (UK)", category: "Regulation" },
      { id: "CARE_CERTIFICATE", label: "Care Certificate Standards (UK)", category: "Training Standards" },
      { id: "AGED_CARE_STANDARDS", label: "Aged Care Quality Standards (Australia)", category: "Professional Standards" },
      { id: "HIQA_STANDARDS", label: "HIQA National Standards (Ireland)", category: "Regulation" },
      { id: "DSD_NORMS", label: "DSD Norms and Standards (South Africa)", category: "Professional Standards" },
      { id: "MOHFW_CARE_INDIA", label: "Ministry of Health & Family Welfare Care Standards (India)", category: "Professional Standards" },
      { id: "FMOH_CARE_NG", label: "Federal Ministry of Health Care Standards (Nigeria)", category: "Professional Standards" },
      { id: "DOH_CARE_PH", label: "DOH Social Care Standards (Philippines)", category: "Professional Standards" },
      { id: "MOPHSR_PK", label: "Ministry of Health Social Care Standards (Pakistan)", category: "Professional Standards" },
      { id: "MOH_CARE_KE", label: "Ministry of Health Care Standards (Kenya)", category: "Professional Standards" },
      { id: "MOFEP_GHANA", label: "Ministry of Finance Care Standards (Ghana)", category: "Professional Standards" },
      { id: "MSF_SINGAPORE", label: "Ministry of Social & Family Development Standards (Singapore)", category: "Professional Standards" },
      { id: "MGLSD_UGANDA", label: "Ministry of Gender Social Care Standards (Uganda)", category: "Professional Standards" },
      { id: "MLSS_JAMAICA", label: "Ministry of Labour & Social Security Standards (Jamaica)", category: "Professional Standards" },
      { id: "JKM_MALAYSIA", label: "Department of Social Welfare Standards (Malaysia)", category: "Professional Standards" },
      { id: "MPSLSW_ZIMBABWE", label: "Ministry of Public Service Care Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "MCDSS_ZAMBIA", label: "Ministry of Community Development Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  YOUTH_WORK: {
    label: "Youth Work",
    description: "Positive relationships, development, and safeguarding young people.",
    reflectionPromptPrefix:
      "You are a youth work reflective coach. Focus on positive relationships, empowerment, and safeguarding.",
    modelsAllowed: ["GIBBS", "ROLFE", "ERA"],
    standards: [
      { id: "NYA_STANDARDS", label: "NYA Professional Standards (UK)", category: "Professional Standards" },
      { id: "YAC_CODE", label: "YAC Code of Ethics (Australia)", category: "Ethics" },
      { id: "CYCC_STANDARDS", label: "Child and Youth Care Certification (Canada)", category: "Professional Standards" },
      { id: "SAFEGUARDING_STANDARDS", label: "Safeguarding Standards (UK)", category: "Safeguarding" },
      { id: "MWCD_INDIA", label: "Ministry of Women & Child Development Standards (India)", category: "Professional Standards" },
      { id: "FMWASD_NIGERIA", label: "Federal Ministry of Women Affairs Youth Standards (Nigeria)", category: "Professional Standards" },
      { id: "DSWD_PH", label: "DSWD Youth Welfare Standards (Philippines)", category: "Professional Standards" },
      { id: "MOHR_PAKISTAN", label: "Ministry of Human Rights Youth Standards (Pakistan)", category: "Professional Standards" },
      { id: "DCS_KENYA", label: "Department of Children's Services Standards (Kenya)", category: "Professional Standards" },
      { id: "MOGCSP_GHANA", label: "Ministry of Gender Youth Development Standards (Ghana)", category: "Professional Standards" },
      { id: "MCCY_SINGAPORE", label: "Ministry of Culture Youth Development Standards (Singapore)", category: "Professional Standards" },
      { id: "MGL SD_YOUTH_UG", label: "Ministry of Gender Youth Standards (Uganda)", category: "Professional Standards" },
      { id: "CDA_JAMAICA", label: "Child Development Agency Standards (Jamaica)", category: "Professional Standards" },
      { id: "KPWKM_MALAYSIA", label: "Ministry of Women Youth Standards (Malaysia)", category: "Professional Standards" },
      { id: "MPSLSW_YOUTH_ZW", label: "Ministry of Public Service Youth Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "MCDSS_YOUTH_ZM", label: "Ministry of Community Development Youth Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  // Professional Services
  LEGAL: {
    label: "Legal / Law",
    description: "Legal reasoning, client care, and ethical practice.",
    reflectionPromptPrefix:
      "You are a legal reflective coach. Focus on legal reasoning, client outcomes, and ethical standards.",
    modelsAllowed: ["STAR", "GIBBS", "ROLFE", "ERA"],
    standards: [
      { id: "SRA_STANDARDS", label: "SRA Standards and Regulations (UK)", category: "Professional Standards" },
      { id: "BSB_HANDBOOK", label: "Bar Standards Board Handbook (UK)", category: "Professional Standards" },
      { id: "LAW_SOCIETY_NSW", label: "Law Society Professional Conduct Rules (Australia - NSW)", category: "Ethics" },
      { id: "NZLS_RULES", label: "NZLS Rules of Conduct (New Zealand)", category: "Professional Standards" },
      { id: "LAW_SOCIETY_ONTARIO", label: "LSO Rules of Professional Conduct (Canada - Ontario)", category: "Ethics" },
      { id: "LAW_SOCIETY_IE", label: "Law Society Professional Conduct (Ireland)", category: "Ethics" },
      { id: "LPC_RULES", label: "Legal Practice Council Rules (South Africa)", category: "Professional Standards" },
      { id: "ABA_MODEL_RULES", label: "ABA Model Rules of Professional Conduct (USA)", category: "Ethics" },
      { id: "STATE_BAR_RULES", label: "State Bar Rules (USA)", category: "Regulation" },
      { id: "BCI_INDIA", label: "Bar Council of India Standards (India)", category: "Professional Standards" },
      { id: "NBA_NIGERIA", label: "Nigerian Bar Association Rules (Nigeria)", category: "Ethics" },
      { id: "IBP_PHILIPPINES", label: "Integrated Bar of the Philippines Code (Philippines)", category: "Ethics" },
      { id: "PBC_PAKISTAN", label: "Pakistan Bar Council Rules (Pakistan)", category: "Professional Standards" },
      { id: "LSK_KENYA", label: "Law Society of Kenya Rules (Kenya)", category: "Ethics" },
      { id: "GBA_GHANA", label: "Ghana Bar Association Code (Ghana)", category: "Ethics" },
      { id: "LAS_SINGAPORE", label: "Law Society of Singapore Rules (Singapore)", category: "Professional Standards" },
      { id: "ULS_UGANDA", label: "Uganda Law Society Code (Uganda)", category: "Ethics" },
      { id: "GLC_JAMAICA", label: "General Legal Council Rules (Jamaica)", category: "Professional Standards" },
      { id: "MBC_MALAYSIA", label: "Malaysian Bar Council Rules (Malaysia)", category: "Ethics" },
      { id: "LSZ_ZIMBABWE", label: "Law Society of Zimbabwe Code (Zimbabwe)", category: "Ethics" },
      { id: "LAZ_ZAMBIA", label: "Law Association of Zambia Rules (Zambia)", category: "Professional Standards" },
    ],
  },

  BUSINESS: {
    label: "Business / Management",
    description: "Strategic thinking, decision-making, and leadership.",
    reflectionPromptPrefix:
      "You are a business reflective coach. Focus on clarity, options, and action steps.",
    modelsAllowed: ["STAR", "GIBBS", "ROLFE", "ERA"],
    standards: [
      { id: "CMI_CODE", label: "CMI Code of Conduct (UK)", category: "Professional Standards" },
      { id: "ILM_STANDARDS", label: "ILM Leadership Standards (UK)", category: "Professional Standards" },
      { id: "AIM_CODE", label: "AIM Code of Conduct (Australia)", category: "Ethics" },
      { id: "CIM_STANDARDS", label: "CIM Professional Standards (Canada)", category: "Professional Standards" },
      { id: "PMI_CODE", label: "PMI Code of Ethics (International)", category: "Ethics" },
      { id: "AIMA_INDIA", label: "All India Management Association Standards (India)", category: "Professional Standards" },
      { id: "NIM_NIGERIA", label: "Nigerian Institute of Management Standards (Nigeria)", category: "Professional Standards" },
      { id: "PMAP_PH", label: "People Management Association Standards (Philippines)", category: "Professional Standards" },
      { id: "PIM_PAKISTAN", label: "Pakistan Institute of Management Standards (Pakistan)", category: "Professional Standards" },
      { id: "KIM_KENYA", label: "Kenya Institute of Management Code (Kenya)", category: "Ethics" },
      { id: "GIM_GHANA", label: "Ghana Institute of Management Standards (Ghana)", category: "Professional Standards" },
      { id: "SIM_SINGAPORE", label: "Singapore Institute of Management Standards (Singapore)", category: "Professional Standards" },
      { id: "UIM_UGANDA", label: "Uganda Institute of Management Standards (Uganda)", category: "Professional Standards" },
      { id: "MIND_JAMAICA", label: "Management Institute for National Development Standards (Jamaica)", category: "Professional Standards" },
      { id: "MIM_MALAYSIA", label: "Malaysian Institute of Management Standards (Malaysia)", category: "Professional Standards" },
      { id: "IMZ_ZIMBABWE", label: "Institute of Management Zimbabwe Code (Zimbabwe)", category: "Ethics" },
      { id: "ZIM_ZAMBIA", label: "Zambia Institute of Management Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  FINANCE: {
    label: "Finance / Accounting",
    description: "Financial analysis, risk management, and regulatory compliance.",
    reflectionPromptPrefix:
      "You are a finance reflective coach. Focus on analytical rigor, risk assessment, and strategic decisions.",
    modelsAllowed: ["STAR", "GIBBS", "ROLFE", "ERA"],
    standards: [
      { id: "ICAEW_CODE", label: "ICAEW Code of Ethics (UK)", category: "Ethics" },
      { id: "FRC_STANDARDS", label: "FRC Ethical Standards (UK)", category: "Ethics" },
      { id: "CPA_CODE_AU", label: "CPA Australia Code of Ethics (Australia)", category: "Ethics" },
      { id: "CAANZ_CODE", label: "CA ANZ Code of Ethics (Australia/New Zealand)", category: "Ethics" },
      { id: "CPA_CODE_CA", label: "CPA Canada Code of Ethics (Canada)", category: "Ethics" },
      { id: "CHARTERED_IE", label: "Chartered Accountants Ireland Code (Ireland)", category: "Ethics" },
      { id: "SAICA_CODE", label: "SAICA Code of Conduct (South Africa)", category: "Ethics" },
      { id: "AICPA_CODE", label: "AICPA Code of Professional Conduct (USA)", category: "Ethics" },
      { id: "CFA_STANDARDS", label: "CFA Institute Standards (International)", category: "Professional Standards" },
      { id: "ICAI_INDIA", label: "Institute of Chartered Accountants Code (India)", category: "Ethics" },
      { id: "ICAN_NIGERIA", label: "Institute of Chartered Accountants Nigeria Code (Nigeria)", category: "Ethics" },
      { id: "PICPA_PH", label: "Philippine Institute of CPAs Code (Philippines)", category: "Ethics" },
      { id: "ICAP_PAKISTAN", label: "Institute of Chartered Accountants Pakistan Code (Pakistan)", category: "Ethics" },
      { id: "ICPAK_KENYA", label: "Institute of CPAs Kenya Code (Kenya)", category: "Ethics" },
      { id: "ICAG_GHANA", label: "Institute of Chartered Accountants Ghana Code (Ghana)", category: "Ethics" },
      { id: "ISCA_SINGAPORE", label: "Institute of Singapore Chartered Accountants Code (Singapore)", category: "Ethics" },
      { id: "ICPAU_UGANDA", label: "Institute of CPAs Uganda Code (Uganda)", category: "Ethics" },
      { id: "ICAJ_JAMAICA", label: "Institute of Chartered Accountants Jamaica Code (Jamaica)", category: "Ethics" },
      { id: "MIA_MALAYSIA", label: "Malaysian Institute of Accountants Code (Malaysia)", category: "Ethics" },
      { id: "ICAZ_ZIMBABWE", label: "Institute of Chartered Accountants Zimbabwe Code (Zimbabwe)", category: "Ethics" },
      { id: "ZICA_ZAMBIA", label: "Zambia Institute of Chartered Accountants Code (Zambia)", category: "Ethics" },
    ],
  },

  ENGINEERING: {
    label: "Engineering",
    description: "Technical problem-solving, design thinking, and safety standards.",
    reflectionPromptPrefix:
      "You are an engineering reflective coach. Focus on problem-solving, design iterations, and safety compliance.",
    modelsAllowed: ["GIBBS", "ERA", "ROLFE", "STAR"],
    standards: [
      { id: "ENGC_UKSPEC", label: "Engineering Council UK-SPEC (UK)", category: "Professional Standards" },
      { id: "ENGINEERS_AU_CODE", label: "Engineers Australia Code of Ethics (Australia)", category: "Ethics" },
      { id: "IPENZ_CODE", label: "Engineering NZ Code of Ethics (New Zealand)", category: "Ethics" },
      { id: "PEO_CODE", label: "PEO Code of Ethics (Canada - Ontario)", category: "Ethics" },
      { id: "ENGINEERS_IE_CODE", label: "Engineers Ireland Code of Ethics (Ireland)", category: "Ethics" },
      { id: "ECSA_CODE", label: "ECSA Code of Conduct (South Africa)", category: "Ethics" },
      { id: "NSPE_CODE", label: "NSPE Code of Ethics (USA)", category: "Ethics" },
      { id: "PE_LICENSE", label: "Professional Engineer License Requirements (USA)", category: "Regulation" },
      { id: "IEI_INDIA", label: "Institution of Engineers India Code (India)", category: "Ethics" },
      { id: "NSE_NIGERIA", label: "Nigerian Society of Engineers Code (Nigeria)", category: "Ethics" },
      { id: "PII_PHILIPPINES", label: "Philippine Institute of Engineers Code (Philippines)", category: "Ethics" },
      { id: "PEC_PAKISTAN", label: "Pakistan Engineering Council Code (Pakistan)", category: "Ethics" },
      { id: "IEK_KENYA", label: "Institution of Engineers Kenya Code (Kenya)", category: "Ethics" },
      { id: "GhIE_GHANA", label: "Ghana Institution of Engineering Code (Ghana)", category: "Ethics" },
      { id: "IES_SINGAPORE", label: "Institution of Engineers Singapore Code (Singapore)", category: "Ethics" },
      { id: "UIPE_UGANDA", label: "Uganda Institution of Professional Engineers Code (Uganda)", category: "Ethics" },
      { id: "JIE_JAMAICA", label: "Jamaica Institution of Engineers Code (Jamaica)", category: "Ethics" },
      { id: "IEM_MALAYSIA", label: "Institution of Engineers Malaysia Code (Malaysia)", category: "Ethics" },
      { id: "ZIE_ZIMBABWE", label: "Zimbabwe Institution of Engineers Code (Zimbabwe)", category: "Ethics" },
      { id: "EIZ_ZAMBIA", label: "Engineering Institution of Zambia Code (Zambia)", category: "Ethics" },
    ],
  },

  TECHNOLOGY: {
    label: "Technology / Software",
    description: "Technical solutions, innovation, and continuous improvement.",
    reflectionPromptPrefix:
      "You are a technology reflective coach. Focus on technical decisions, user impact, and iterative improvement.",
    modelsAllowed: ["GIBBS", "ERA", "ROLFE", "STAR"],
    standards: [
      { id: "BCS_CODE", label: "BCS Code of Conduct (UK)", category: "Ethics" },
      { id: "ACS_CODE", label: "ACS Code of Ethics (Australia)", category: "Ethics" },
      { id: "IITP_CODE", label: "IITP Code of Ethics (New Zealand)", category: "Ethics" },
      { id: "CIPS_CODE", label: "CIPS Code of Ethics (Canada)", category: "Ethics" },
      { id: "ACM_CODE", label: "ACM Code of Ethics (International)", category: "Ethics" },
      { id: "IEEE_CODE", label: "IEEE Code of Ethics (International)", category: "Ethics" },
      { id: "CSI_INDIA", label: "Computer Society of India Code (India)", category: "Ethics" },
      { id: "CPN_NIGERIA", label: "Computer Professionals Nigeria Code (Nigeria)", category: "Ethics" },
      { id: "PSITE_PH", label: "Philippine Society of IT Educators Code (Philippines)", category: "Ethics" },
      { id: "PASHA_PAKISTAN", label: "Pakistan Software Houses Association Code (Pakistan)", category: "Ethics" },
      { id: "CISK_KENYA", label: "Computer Society of Kenya Code (Kenya)", category: "Ethics" },
      { id: "GCS_GHANA", label: "Ghana Computer Society Code (Ghana)", category: "Ethics" },
      { id: "SCS_SINGAPORE", label: "Singapore Computer Society Code (Singapore)", category: "Ethics" },
      { id: "ICTAU_UGANDA", label: "ICT Association of Uganda Code (Uganda)", category: "Ethics" },
      { id: "CSJM_JAMAICA", label: "Computing Society of Jamaica Code (Jamaica)", category: "Ethics" },
      { id: "PIKOM_MALAYSIA", label: "National Tech Association Code (Malaysia)", category: "Ethics" },
      { id: "CSZIM_ZIMBABWE", label: "Computer Society of Zimbabwe Code (Zimbabwe)", category: "Ethics" },
      { id: "ZICTA_ZAMBIA", label: "Zambia ICT Authority Code (Zambia)", category: "Ethics" },
    ],
  },

  // Research & Science
  RESEARCH: {
    label: "Research / Science",
    description: "Critical inquiry, methodology, and evidence-based conclusions.",
    reflectionPromptPrefix:
      "You are a research reflective coach. Focus on methodology, critical analysis, and evidence synthesis.",
    modelsAllowed: ["GIBBS", "ROLFE", "ERA"],
    standards: [
      { id: "UKRIO_CODE", label: "UKRIO Code of Practice (UK)", category: "Research Integrity" },
      { id: "AUSTRALIAN_CODE", label: "Australian Code for Research (Australia)", category: "Research Ethics" },
      { id: "NHMRC_CODE", label: "NHMRC Code of Conduct (Australia)", category: "Research Ethics" },
      { id: "TRI_COUNCIL", label: "Tri-Council Policy Statement (Canada)", category: "Research Ethics" },
      { id: "HRC_GUIDELINES", label: "HRC Guidelines on Ethics (New Zealand)", category: "Research Ethics" },
      { id: "SINGAPORE_STATEMENT", label: "Singapore Statement on Research Integrity (International)", category: "Research Ethics" },
      { id: "ICMR_INDIA", label: "Indian Council of Medical Research Guidelines (India)", category: "Research Ethics" },
      { id: "NHREC_NIGERIA", label: "National Health Research Ethics Committee Guidelines (Nigeria)", category: "Research Ethics" },
      { id: "PNHRS_PH", label: "Philippine National Health Research System Ethics (Philippines)", category: "Research Ethics" },
      { id: "NHSREC_PAKISTAN", label: "National Health Services Research Ethics (Pakistan)", category: "Research Ethics" },
      { id: "NACOSTI_KENYA", label: "National Commission for Science & Technology Standards (Kenya)", category: "Research Ethics" },
      { id: "CSIR_GHANA", label: "Council for Scientific & Industrial Research Code (Ghana)", category: "Research Ethics" },
      { id: "NRF_SINGAPORE", label: "National Research Foundation Ethics Guidelines (Singapore)", category: "Research Ethics" },
      { id: "UNCST_UGANDA", label: "Uganda National Council for Science & Technology Ethics (Uganda)", category: "Research Ethics" },
      { id: "PIOJ_JAMAICA", label: "Planning Institute Research Ethics (Jamaica)", category: "Research Ethics" },
      { id: "MOSTI_MALAYSIA", label: "Ministry of Science Research Ethics (Malaysia)", category: "Research Ethics" },
      { id: "MHRTEC_ZIMBABWE", label: "Medical Research Council Ethics (Zimbabwe)", category: "Research Ethics" },
      { id: "NSTC_ZAMBIA", label: "National Science & Technology Council Ethics (Zambia)", category: "Research Ethics" },
    ],
  },

  // Creative & Arts
  CREATIVE: {
    label: "Creative / Arts",
    description: "Creative process, artistic development, and expressive practice.",
    reflectionPromptPrefix:
      "You are a creative arts reflective coach. Focus on creative process, artistic growth, and expressive exploration.",
    modelsAllowed: ["FREE", "GIBBS", "ERA", "ROLFE"],
    standards: [
      { id: "ARTS_COUNCIL_STANDARDS", label: "Arts Council Standards (UK)", category: "Professional Standards" },
      { id: "CREATIVE_NZ_STANDARDS", label: "Creative NZ Standards (New Zealand)", category: "Professional Standards" },
      { id: "CANADA_COUNCIL", label: "Canada Council Standards (Canada)", category: "Professional Standards" },
      { id: "LALIT_KALA_INDIA", label: "Lalit Kala Akademi Standards (India)", category: "Professional Standards" },
      { id: "NAC_NIGERIA", label: "National Arts Council Standards (Nigeria)", category: "Professional Standards" },
      { id: "NCCA_PH", label: "National Commission for Culture & the Arts Standards (Philippines)", category: "Professional Standards" },
      { id: "PNCA_PAKISTAN", label: "Pakistan National Council of the Arts Standards (Pakistan)", category: "Professional Standards" },
      { id: "KENAC_KENYA", label: "Kenya National Arts Council Standards (Kenya)", category: "Professional Standards" },
      { id: "NAC_GHANA", label: "National Arts Council of Ghana Standards (Ghana)", category: "Professional Standards" },
      { id: "NAC_SINGAPORE", label: "National Arts Council Singapore Standards (Singapore)", category: "Professional Standards" },
      { id: "UNCC_UGANDA", label: "Uganda National Cultural Centre Standards (Uganda)", category: "Professional Standards" },
      { id: "JCDC_JAMAICA", label: "Jamaica Cultural Development Commission Standards (Jamaica)", category: "Professional Standards" },
      { id: "NAC_MALAYSIA", label: "National Arts Council Malaysia Standards (Malaysia)", category: "Professional Standards" },
      { id: "NAC_ZIMBABWE", label: "National Arts Council Zimbabwe Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "NAC_ZAMBIA", label: "National Arts Council Zambia Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  // Public & Non-Profit
  PUBLIC_SERVICE: {
    label: "Public Service",
    description: "Public accountability, policy impact, and civic duty.",
    reflectionPromptPrefix:
      "You are a public service reflective coach. Focus on public value, accountability, and service delivery.",
    modelsAllowed: ["STAR", "GIBBS", "ROLFE", "ERA"],
    standards: [
      { id: "CIVIL_SERVICE_CODE_UK", label: "Civil Service Code (UK)", category: "Professional Standards" },
      { id: "APS_CODE", label: "APS Code of Conduct (Australia)", category: "Ethics" },
      { id: "SSC_CODE", label: "State Services Code (New Zealand)", category: "Professional Standards" },
      { id: "VALUES_ETHICS_CODE_CA", label: "Values and Ethics Code (Canada)", category: "Ethics" },
      { id: "CPSI_CODE", label: "CPSI Code of Conduct (Ireland)", category: "Ethics" },
      { id: "CSS_INDIA", label: "Central Secretariat Service Code (India)", category: "Ethics" },
      { id: "PSC_NIGERIA", label: "Public Service Code of Conduct (Nigeria)", category: "Ethics" },
      { id: "CSC_PH", label: "Civil Service Commission Code (Philippines)", category: "Ethics" },
      { id: "FPSC_PAKISTAN", label: "Federal Public Service Commission Standards (Pakistan)", category: "Professional Standards" },
      { id: "PSC_KENYA", label: "Public Service Commission Values (Kenya)", category: "Ethics" },
      { id: "OSP_GHANA", label: "Office of the Special Prosecutor Standards (Ghana)", category: "Professional Standards" },
      { id: "PSD_SINGAPORE", label: "Public Service Division Code (Singapore)", category: "Ethics" },
      { id: "PSC_UGANDA", label: "Public Service Commission Code (Uganda)", category: "Ethics" },
      { id: "OPM_JAMAICA", label: "Office of the Prime Minister Service Standards (Jamaica)", category: "Professional Standards" },
      { id: "PSD_MALAYSIA", label: "Public Service Department Code (Malaysia)", category: "Ethics" },
      { id: "PSC_ZIMBABWE", label: "Public Service Commission Code (Zimbabwe)", category: "Ethics" },
      { id: "PSC_ZAMBIA", label: "Public Service Commission Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  NON_PROFIT: {
    label: "Non-Profit / Charity",
    description: "Mission-driven work, stakeholder impact, and resource stewardship.",
    reflectionPromptPrefix:
      "You are a non-profit reflective coach. Focus on mission impact, stakeholder engagement, and sustainable practice.",
    modelsAllowed: ["STAR", "GIBBS", "ROLFE", "ERA"],
    standards: [
      { id: "CHARITY_CODE_UK", label: "Charity Governance Code (UK)", category: "Governance" },
      { id: "ACNC_STANDARDS", label: "ACNC Governance Standards (Australia)", category: "Governance" },
      { id: "CHARITIES_SERVICES_NZ", label: "Charities Services Standards (New Zealand)", category: "Governance" },
      { id: "CRA_GUIDANCE", label: "CRA Charity Guidance (Canada)", category: "Regulation" },
      { id: "CHARITIES_REGULATOR_IE", label: "Charities Regulator Guidelines (Ireland)", category: "Governance" },
      { id: "NPO_ACT_ZA", label: "NPO Act Requirements (South Africa)", category: "Regulation" },
      { id: "CREDAI_INDIA", label: "Credibility Alliance NGO Standards (India)", category: "Governance" },
      { id: "CAC_NIGERIA", label: "Corporate Affairs Commission NGO Standards (Nigeria)", category: "Regulation" },
      { id: "SEC_NGO_PH", label: "Securities and Exchange Commission NGO Standards (Philippines)", category: "Regulation" },
      { id: "PVCA_PAKISTAN", label: "Pakistan Voluntary Community Act Standards (Pakistan)", category: "Regulation" },
      { id: "NGO_BOARD_KENYA", label: "NGO Coordination Board Standards (Kenya)", category: "Governance" },
      { id: "DSW_GHANA", label: "Department of Social Welfare NGO Standards (Ghana)", category: "Governance" },
      { id: "NCSS_SINGAPORE", label: "National Council of Social Service Standards (Singapore)", category: "Governance" },
      { id: "NGO_BOARD_UGANDA", label: "NGO Board Uganda Standards (Uganda)", category: "Governance" },
      { id: "CAC_JAMAICA", label: "Companies Office of Jamaica Charity Standards (Jamaica)", category: "Regulation" },
      { id: "ROS_MALAYSIA", label: "Registrar of Societies NGO Standards (Malaysia)", category: "Regulation" },
      { id: "PVO_ACT_ZIMBABWE", label: "Private Voluntary Organizations Act Standards (Zimbabwe)", category: "Regulation" },
      { id: "NGO_ACT_ZAMBIA", label: "NGO Act Registration Standards (Zambia)", category: "Regulation" },
    ],
  },

  // Customer-Facing
  CUSTOMER_SERVICE: {
    label: "Customer Service",
    description: "Client relations, problem resolution, and service excellence.",
    reflectionPromptPrefix:
      "You are a customer service reflective coach. Focus on client satisfaction, problem-solving, and service quality.",
    modelsAllowed: ["STAR", "ROLFE", "ERA", "GIBBS"],
    standards: [
      { id: "ICS_STANDARDS", label: "ICS Professional Standards (UK)", category: "Professional Standards" },
      { id: "ISO_18295", label: "ISO 18295 Customer Contact Centers (International)", category: "Professional Standards" },
      { id: "CCAI_INDIA", label: "Customer Care Association India Standards (India)", category: "Professional Standards" },
      { id: "CCAN_NIGERIA", label: "Customer Care Association Nigeria Standards (Nigeria)", category: "Professional Standards" },
      { id: "PCCI_CS_PH", label: "Philippine Chamber of Commerce Customer Service Standards (Philippines)", category: "Professional Standards" },
      { id: "FPCCI_PAKISTAN", label: "Federation of Chambers Customer Service Standards (Pakistan)", category: "Professional Standards" },
      { id: "KAM_KENYA", label: "Kenya Association of Manufacturers Service Standards (Kenya)", category: "Professional Standards" },
      { id: "AGI_GHANA", label: "Association of Ghana Industries Service Standards (Ghana)", category: "Professional Standards" },
      { id: "SPRING_SINGAPORE", label: "SPRING Singapore Service Excellence Standards (Singapore)", category: "Professional Standards" },
      { id: "PSFU_UGANDA", label: "Private Sector Foundation Service Standards (Uganda)", category: "Professional Standards" },
      { id: "JBDC_JAMAICA", label: "Jamaica Business Development Service Standards (Jamaica)", category: "Professional Standards" },
      { id: "FMM_MALAYSIA", label: "Federation of Malaysian Manufacturers Service Standards (Malaysia)", category: "Professional Standards" },
      { id: "CZI_ZIMBABWE", label: "Confederation of Zimbabwe Industries Service Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "ZAM_ZAMBIA", label: "Zambia Association of Manufacturers Service Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  HOSPITALITY: {
    label: "Hospitality",
    description: "Guest experience, service delivery, and operational excellence.",
    reflectionPromptPrefix:
      "You are a hospitality reflective coach. Focus on guest experience, team coordination, and service standards.",
    modelsAllowed: ["STAR", "ROLFE", "ERA", "GIBBS"],
    standards: [
      { id: "IOH_STANDARDS", label: "Institute of Hospitality Standards (UK)", category: "Professional Standards" },
      { id: "AHA_CODE", label: "AHA Code of Ethics (Australia)", category: "Ethics" },
      { id: "AHLA_STANDARDS", label: "AHLA Standards (USA)", category: "Professional Standards" },
      { id: "FHRAI_INDIA", label: "Federation of Hotel & Restaurant Associations Standards (India)", category: "Professional Standards" },
      { id: "FHAN_NIGERIA", label: "Federation of Hospitality Association Nigeria Standards (Nigeria)", category: "Professional Standards" },
      { id: "HRAP_PH", label: "Hotel & Restaurant Association Philippines Standards (Philippines)", category: "Professional Standards" },
      { id: "PHMA_PAKISTAN", label: "Pakistan Hotels & Motels Association Standards (Pakistan)", category: "Professional Standards" },
      { id: "KHA_KENYA", label: "Kenya Hotel Association Standards (Kenya)", category: "Professional Standards" },
      { id: "GHATOF_GHANA", label: "Ghana Hotels Association Standards (Ghana)", category: "Professional Standards" },
      { id: "SHA_SINGAPORE", label: "Singapore Hotel Association Standards (Singapore)", category: "Professional Standards" },
      { id: "UHA_UGANDA", label: "Uganda Hotel Association Standards (Uganda)", category: "Professional Standards" },
      { id: "JHTA_JAMAICA", label: "Jamaica Hotel & Tourist Association Standards (Jamaica)", category: "Professional Standards" },
      { id: "MAH_MALAYSIA", label: "Malaysian Association of Hotels Standards (Malaysia)", category: "Professional Standards" },
      { id: "HAZ_ZIMBABWE", label: "Hospitality Association of Zimbabwe Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "HACZ_ZAMBIA", label: "Hotel & Catering Association Zambia Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  // Leadership & Coaching
  LEADERSHIP: {
    label: "Leadership / Coaching",
    description: "Team development, strategic vision, and organizational impact.",
    reflectionPromptPrefix:
      "You are a leadership reflective coach. Focus on strategic thinking, team development, and organizational outcomes.",
    modelsAllowed: ["STAR", "GIBBS", "ROLFE", "ERA"],
    standards: [
      { id: "ICF_CORE_COMP", label: "ICF Core Competencies (International)", category: "Professional Standards" },
      { id: "EMCC_CODE", label: "EMCC Code of Ethics (Europe/International)", category: "Ethics" },
      { id: "CMI_LEADERSHIP", label: "CMI Leadership Standards (UK)", category: "Professional Standards" },
      { id: "CCE_STANDARDS", label: "CCE Standards (Canada)", category: "Professional Standards" },
      { id: "ICAI_LEADERSHIP_INDIA", label: "Indian Centre for Leadership Development Standards (India)", category: "Professional Standards" },
      { id: "CIPM_NIGERIA", label: "Chartered Institute of Personnel Management Nigeria Standards (Nigeria)", category: "Professional Standards" },
      { id: "PMAP_LEADERSHIP_PH", label: "People Management Association Leadership Standards (Philippines)", category: "Professional Standards" },
      { id: "PIHR_PAKISTAN", label: "Pakistan Institute of HR Leadership Standards (Pakistan)", category: "Professional Standards" },
      { id: "IHRM_KENYA", label: "Institute of Human Resource Management Kenya Standards (Kenya)", category: "Professional Standards" },
      { id: "IHRMP_GHANA", label: "Institute of HR Management Practitioners Ghana Standards (Ghana)", category: "Professional Standards" },
      { id: "SHRI_SINGAPORE", label: "Singapore HR Institute Leadership Standards (Singapore)", category: "Professional Standards" },
      { id: "IPMU_UGANDA", label: "Institute of Personnel Management Uganda Standards (Uganda)", category: "Professional Standards" },
      { id: "HRMAJ_JAMAICA", label: "Human Resource Management Association Jamaica Standards (Jamaica)", category: "Professional Standards" },
      { id: "MIHRM_MALAYSIA", label: "Malaysian Institute of HR Management Standards (Malaysia)", category: "Professional Standards" },
      { id: "IPMZ_ZIMBABWE", label: "Institute of Personnel Management Zimbabwe Standards (Zimbabwe)", category: "Professional Standards" },
      { id: "ZIHRM_ZAMBIA", label: "Zambia Institute of HR Management Standards (Zambia)", category: "Professional Standards" },
    ],
  },

  // Other
  OTHER: {
    label: "Other",
    description: "Custom professional context - adapt reflection to your needs.",
    reflectionPromptPrefix:
      "You are a reflective coach. Keep answers practical, kind, and concise.",
  },
};

// ---------- Reflection model configuration ----------

export const MODEL_CONFIG: Record<ReflectionModelId, ReflectionModelConfig> = {
  GIBBS: {
    id: "GIBBS",
    title: "Gibbs",
    description: "Classic reflective cycle: description → feelings → evaluation → analysis → conclusion → action plan.",
    stages: [
      { id: S.Description, label: "Description", prompt: "What happened?", placeholder: "Describe the situation..." },
      { id: S.Feelings, label: "Feelings", prompt: "What were you thinking and feeling?", placeholder: "How did it affect you?" },
      { id: S.Evaluation, label: "Evaluation", prompt: "What was good and bad about the experience?", placeholder: "What worked / didn't work?" },
      { id: S.Analysis, label: "Analysis", prompt: "What sense can you make of the situation?", placeholder: "What was really going on?" },
      { id: S.Conclusion, label: "Conclusion", prompt: "What else could you have done?", placeholder: "What would you change?" },
      { id: S.ActionPlan, label: "Action Plan", prompt: "If it arose again, what would you do?", placeholder: "Concrete next steps..." },
    ],
  },

  SBAR: {
    id: "SBAR",
    title: "SBAR",
    description: "Situation → Background → Assessment → Recommendation.",
    stages: [
      { id: S.SBAR_Situation, label: "Situation", prompt: "What is the situation?", placeholder: "State the situation clearly..." },
      { id: S.SBAR_Background, label: "Background", prompt: "What background is relevant?", placeholder: "Key context..." },
      { id: S.SBAR_Assessment, label: "Assessment", prompt: "What is your assessment?", placeholder: "What do you think is happening?" },
      { id: S.SBAR_Recommendation, label: "Recommendation", prompt: "What do you recommend next?", placeholder: "Next action / decision..." },
    ],
  },

  ERA: {
    id: "ERA",
    title: "ERA",
    description: "Experience → Reflection → Action.",
    stages: [
      { id: S.ERA_Experience, label: "Experience", prompt: "Describe the experience.", placeholder: "What happened?" },
      { id: S.ERA_Reflection, label: "Reflection", prompt: "What did you learn?", placeholder: "What stood out and why?" },
      { id: S.ERA_Action, label: "Action", prompt: "What will you do next?", placeholder: "Your next steps..." },
    ],
  },

  ROLFE: {
    id: "ROLFE",
    title: "Rolfe",
    description: "What? → So what? → Now what?",
    stages: [
      { id: S.ROLFE_What, label: "What?", prompt: "What happened?", placeholder: "Describe it..." },
      { id: S.ROLFE_SoWhat, label: "So what?", prompt: "Why does it matter?", placeholder: "Meaning/impact..." },
      { id: S.ROLFE_NowWhat, label: "Now what?", prompt: "What will you do next?", placeholder: "Actionable next steps..." },
    ],
  },

  STAR: {
    id: "STAR",
    title: "STAR",
    description: "Situation → Task → Action → Result.",
    stages: [
      { id: S.STAR_Situation, label: "Situation", prompt: "What was the situation?", placeholder: "Context..." },
      { id: S.STAR_Task, label: "Task", prompt: "What was your task?", placeholder: "Your responsibility..." },
      { id: S.STAR_Action, label: "Action", prompt: "What did you do?", placeholder: "Your actions..." },
      { id: S.STAR_Result, label: "Result", prompt: "What happened as a result?", placeholder: "Outcome..." },
    ],
  },

  SOAP: {
    id: "SOAP",
    title: "SOAP",
    description: "Subjective → Objective → Assessment → Plan.",
    stages: [
      { id: S.SOAP_Subjective, label: "Subjective", prompt: "What's the subjective experience?", placeholder: "Symptoms/feelings..." },
      { id: S.SOAP_Objective, label: "Objective", prompt: "What objective data exists?", placeholder: "Facts/observations..." },
      { id: S.SOAP_Assessment, label: "Assessment", prompt: "What's your assessment?", placeholder: "Interpretation..." },
      { id: S.SOAP_Plan, label: "Plan", prompt: "What's the plan?", placeholder: "Next steps..." },
    ],
  },

  MORNING: {
    id: "MORNING",
    title: "Morning Check-in",
    description: "Energy → Focus → Intention.",
    stages: [
      { id: S.MORNING_Energy, label: "Energy", prompt: "How's your energy?", placeholder: "0–10 and why..." },
      { id: S.MORNING_Focus, label: "Focus", prompt: "What do you need to focus on today?", placeholder: "Top priorities..." },
      { id: S.MORNING_Intention, label: "Intention", prompt: "What's your intention for the day?", placeholder: "A guiding intention..." },
    ],
  },

  EVENING: {
    id: "EVENING",
    title: "Evening Review",
    description: "Wins → Growth → Unwind.",
    stages: [
      { id: S.EVENING_Wins, label: "Wins", prompt: "What went well today?", placeholder: "Small and big wins..." },
      { id: S.EVENING_Growth, label: "Growth", prompt: "What did you learn today?", placeholder: "Lessons..." },
      { id: S.EVENING_Unwind, label: "Unwind", prompt: "What do you need to release?", placeholder: "Anything to let go of..." },
    ],
  },

  FREE: {
    id: "FREE",
    title: "Free Writing",
    description: "Open reflection, no structure.",
    stages: [{ id: S.FREE_Writing, label: "Write", prompt: "Write freely.", placeholder: "Just start..." }],
  },

  CUSTOM_1: {
    id: "CUSTOM_1",
    title: "Custom 1",
    description: "Custom model placeholder.",
    stages: [
      { id: S.CUSTOM_Stage1, label: "Stage 1", prompt: "Custom stage 1 prompt.", placeholder: "..." },
      { id: S.CUSTOM_Stage2, label: "Stage 2", prompt: "Custom stage 2 prompt.", placeholder: "..." },
      { id: S.CUSTOM_Stage3, label: "Stage 3", prompt: "Custom stage 3 prompt.", placeholder: "..." },
    ],
  },

  CUSTOM_2: {
    id: "CUSTOM_2",
    title: "Custom 2",
    description: "Custom model placeholder.",
    stages: [{ id: S.FREE_Writing, label: "Write", prompt: "Custom writing.", placeholder: "..." }],
  },

  CUSTOM_3: {
    id: "CUSTOM_3",
    title: "Custom 3",
    description: "Custom model placeholder.",
    stages: [{ id: S.FREE_Writing, label: "Write", prompt: "Custom writing.", placeholder: "..." }],
  },
};

// ---------- Achievements (minimal, to unblock gamificationService) ----------

export const ACHIEVEMENTS: Achievement[] = [
  { id: "FIRST_ENTRY", title: "First Entry", description: "You made your first entry." },
  { id: "THREE_DAY_STREAK", title: "3-Day Streak", description: "You showed up three days in a row." },
  { id: "TEN_ENTRIES", title: "10 Entries", description: "You've written ten entries." },
  { id: "CPD_1H", title: "1 Hour CPD", description: "You logged 60 minutes of CPD reflection." },
];
